In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Importing the customized weather data file containg Weather from 1991 - 2019 (June)

In [2]:
weather_data_file = pd.read_csv('/Users/owner/Documents/Columbia/climate/synPUF/weather_data.csv')
#weather_data_file['DateTime'] = pd.to_datetime(weather_data_file['DateTime'])
weather_data_file

         DateTime      DPT  Mean Temp  MaxTemp  Apparent temp
0      1991-01-01  -7.3283     0.1371   3.1429      -1.696052
1      1991-01-02  -2.5343     4.1118   8.0529       1.531396
2      1991-01-03  -6.4329     2.2022   4.9429       0.168134
3      1991-01-04 -10.3759     0.0869   2.3530      -0.920434
4      1991-01-05  -7.5598     1.0023   4.5931      -0.783310
5      1991-01-06  -1.3155     4.6368   7.8328       1.981456
6      1991-01-07  -7.2828     1.6072   5.6529      -0.244944
7      1991-01-08  -8.9994    -1.5236   0.8322      -2.929324
8      1991-01-09  -2.2098     1.1372   3.2333      -1.448910
9      1991-01-10  -5.7679     0.3022   3.6827      -1.844603
10     1991-01-11  -5.5931    -0.8232   4.4726      -2.993634
11     1991-01-12  -0.4330     3.9920   6.2124       1.316917
12     1991-01-13  -7.0044     0.1072   3.6931      -1.796800
13     1991-01-14  -8.4141    -0.4580   2.6831      -2.026057
14     1991-01-15  -2.5359     2.3422   5.3332      -0.227462
15     1991-01-16   1.1386     4.0472   8.0030       1.388752
16     1991-01-17  -0.3442     5.1923   8.7629       2.508959
17     1991-01-18  -5.4944     2.3025   4.5433       0.096568
18     1991-01-19  -4.3978     3.6269   8.1223       1.247050
19     1991-01-20  -1.2517     5.8467  11.4223       3.181591
20     1991-01-21  -6.1679     0.1024   5.9332      -1.970157
21     1991-01-22 -19.9717    -7.3132  -4.2874      -3.820628
22     1991-01-23 -11.3388    -3.6231   1.8526      -4.288265
23     1991-01-24  -8.6838     0.4322   3.7232      -1.070645
24     1991-01-25 -18.8039    -3.7928  -1.2272      -1.014167
25     1991-01-26 -13.3808    -3.3378   0.7430      -3.232372
26     1991-01-27  -8.2580     0.1419   3.3225      -1.469575
27     1991-01-28  -2.4243     4.1116   8.1826       1.522852
28     1991-01-29  -3.6344     3.5621   7.7830       1.088823
29     1991-01-30   2.5314     6.3225  10.8733       3.728607
...           ...      ...        ...      ...            ...
10350  2019-05-04  12.4075    16.1500  20.3500      15.754475
10351  2019-05-05   9.9462    11.8500  13.2500      10.638481
10352  2019-05-06   9.3419    16.3000  20.9500      14.883448
10353  2019-05-07  11.0887    17.0000  20.8500      16.125277
10354  2019-05-08   9.5130    16.2000  20.9500      14.833407
10355  2019-05-09   6.7907    13.7000  15.1500      11.669338
10356  2019-05-10  13.4533    18.7000  23.5500      18.702967
10357  2019-05-11   9.3016    14.9500  20.8500      13.530052
10358  2019-05-12   5.6671     7.5000   8.9500       5.292375
10359  2019-05-13   5.1995     8.0000   9.0500       5.711632
10360  2019-05-14   4.7780     9.2500  11.1500       6.889788
10361  2019-05-15   6.1975    15.4500  20.6500      13.290958
10362  2019-05-16   8.0485    18.4500  22.6500      16.676409
10363  2019-05-17  13.2275    19.4500  24.6500      19.356291
10364  2019-05-18   9.5732    19.5000  23.9500      18.131186
10365  2019-05-19  14.4685    21.3000  25.1500      21.721064
10366  2019-05-20  16.3368    22.1500  29.8500      23.446533
10367  2019-05-21   6.4471    17.3000  22.2500      15.178146
10368  2019-05-22   6.3367    18.5000  23.6500      16.349353
10369  2019-05-23  13.6057    18.0000  22.6500      18.070261
10370  2019-05-24  11.6253    18.5000  23.4500      17.802758
10371  2019-05-25  11.0241    18.2500  21.4500      17.345921
10372  2019-05-26  15.9088    24.4500  30.6500      25.521576
10373  2019-05-27  11.5558    22.4000  27.3500      21.654709
10374  2019-05-28  14.3576    19.1000  21.7500      19.485352
10375  2019-05-29  15.3559    16.8500  20.2500      17.702696
10376  2019-05-30  14.8781    17.7500  20.5500      18.376275
10377  2019-05-31  14.4969    22.2000  26.7500      22.628250
10378  2019-06-01  14.4846    21.8000  25.8500      22.225196
10379  2019-06-02  16.0431    21.3000  27.4500      22.456130

[10380 rows x 5 columns]

# Apparent temperature above set Threshold

In [3]:
# Here we opted for AT above 33 degree C
weather_file_above_threshold = weather_data_file[weather_data_file['Apparent temp'] > 33]
weather_file_above_threshold

         DateTime      DPT  Mean Temp  MaxTemp  Apparent temp
200    1991-07-20  20.2884    30.1610  36.4549      33.623807
201    1991-07-21  20.9882    30.1809  35.8746      34.085534
203    1991-07-23  22.2694    30.1111  35.5850      34.864104
918    1993-07-07  22.2687    29.8566  34.9479      34.610654
919    1993-07-08  21.7611    31.6063  36.3469      36.007908
920    1993-07-09  19.3806    32.3365  37.4773      35.235278
921    1993-07-10  20.2286    31.6914  37.5471      35.107954
970    1993-08-28  21.6717    29.2173  34.9624      33.573834
1265   1994-06-19  19.6946    30.1261  35.2426      33.225866
1284   1994-07-08  22.5519    29.3566  33.6633      34.307860
1285   1994-07-09  22.2383    28.8062  33.3326      33.545855
1655   1995-07-14  20.7647    29.6513  36.2968      33.416336
1656   1995-07-15  22.6235    31.7269  38.2673      36.713427
1667   1995-07-26  22.4758    28.9965  32.6266      33.897493
1668   1995-07-27  21.7881    29.8467  33.1371      34.276856
1669   1995-07-28  22.2804    29.1561  31.9466      33.922332
1670   1995-07-29  21.8158    30.1614  33.8566      34.608147
1675   1995-08-03  21.5231    29.5331  34.2076      33.789532
2387   1997-07-15  20.6909    29.8889  35.7787      33.605701
2388   1997-07-16  21.3333    29.8587  34.2687      33.988726
2389   1997-07-17  19.5592    30.1135  34.5879      33.132022
2419   1997-08-16  22.3254    28.7675  35.3310      33.566774
3106   1999-07-04  22.5213    30.8131  36.1088      35.734518
3107   1999-07-05  22.5430    32.7128  37.9979      37.637782
3108   1999-07-06  21.7924    31.5378  36.9685      35.960676
3146   1999-08-13  22.1396    28.3327  31.8878      33.008181
3858   2001-07-25  21.9764    29.8826  34.7863      34.438625
3871   2001-08-07  20.5326    29.3802  35.5342      33.000210
3872   2001-08-08  21.1636    30.4502  35.7546      34.466338
3873   2001-08-09  20.7511    31.1055  36.6652      34.853172
...           ...      ...        ...      ...            ...
8234   2013-07-18  19.6346    31.4111  38.7649      34.467051
8235   2013-07-19  20.4954    32.1772  39.0952      35.757077
8236   2013-07-20  20.7304    31.4933  36.9967      35.225507
8965   2015-07-19  18.4141    31.0241  34.4315      33.371865
8966   2015-07-20  22.1983    30.4190  34.3315      35.121783
8974   2015-07-28  20.6575    29.5592  34.2316      33.256849
8975   2015-07-29  20.7373    30.3287  34.6812      34.072273
9334   2016-07-22  20.0469    30.3597  34.8854      33.672278
9337   2016-07-25  22.3789    28.3997  34.0354      33.237774
9353   2016-08-10  21.7220    28.6762  30.8089      33.069376
9354   2016-08-11  23.0205    29.1112  34.0089      34.390667
9355   2016-08-12  23.4715    30.5362  34.6089      36.127926
9356   2016-08-13  23.9413    31.8512  35.6589      37.775836
9357   2016-08-14  22.2425    30.2562  34.8889      34.990014
9358   2016-08-15  21.5992    29.3762  33.0289      33.683782
9696   2017-07-19  21.3950    29.3367  33.5270      33.510194
9697   2017-07-20  20.7310    29.7537  34.8590      33.496726
9698   2017-07-21  20.7552    29.5747  33.7770      33.334160
10043  2018-07-01  20.8945    30.3668  35.5044      34.210275
10044  2018-07-02  21.9748    30.1768  34.8174      34.729984
10045  2018-07-03  23.0943    28.9478  33.0745      34.280318
10058  2018-07-16  21.7471    28.6853  32.4954      33.095114
10079  2018-08-06  21.9798    29.2395  33.4449      33.801671
10080  2018-08-07  23.1125    27.7245  32.0139      33.077224
10081  2018-08-08  22.7500    28.0130  32.3509      33.109628
10101  2018-08-28  22.3603    30.3640  34.6349      35.177556
10102  2018-08-29  22.5407    29.9880  33.9239      34.927744
10107  2018-09-03  21.5176    28.7953  32.8329      33.052537
10109  2018-09-05  21.7569    28.7958  32.2679      33.211474
10110  2018-09-06  22.3709    28.8408  34.1399      33.670750

[97 rows x 5 columns]

In [4]:
def final_table (table):
    dicts = {}
    index_list = list(table.index)
    consecutive_days_list_case = []
    non_consecutive_days_list = []
    for i in range(len(index_list)):
    #    print (i)
        try:
            if (index_list[i+1] - index_list[i] <= 2) | (index_list[i] - index_list[i-1] <= 2):
                 consecutive_days_list_case.append(index_list[i])
            else:
                non_consecutive_days_list.append(i)
        except:
            consecutive_days_list_case.append(index_list[i])

    spl = [0]+[i for i in range(1,len(consecutive_days_list_case)) if consecutive_days_list_case[i]-consecutive_days_list_case[i-1]>2]+[None]
    
    heatwave_days_cluster =([consecutive_days_list_case[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]])            
    #print (heatwave_days_cluster)
    
    refined_list = weather_file_above_threshold.drop(weather_file_above_threshold.index[non_consecutive_days_list])

    # Grouping the days
    
    groups = [consecutive_days_list_case[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]]
    #groups
    dicts = {}
    for i in range(len(groups)):
        dicts[i] = groups[i]
    #print(dicts) 
    
    weather_data_2 = table
    df_weather = pd.DataFrame.from_dict(dicts, orient = 'index')
    #df_weather
    new_df_weather = df_weather.stack().reset_index(level=1, drop=True).to_frame('ttt')
    new_df_weather['index_count'] = new_df_weather.index
    #grouped = new_df_weather.groupby('index_count')
    #for name in grouped:
    #    print (name)
    #   print (group)

    #weather_data_2
    new_df_weather.dtypes
    new_df_weather['ttt'] = new_df_weather['ttt'].astype(int)
    new_df_weather = new_df_weather.set_index('ttt')
    #print (new_df_weather)

    
    
    
    #refined_lists = refined_list.join(new_df_weather)

    refined_list['index_count'] = new_df_weather['index_count']
    refined_list['index_count'] = refined_list['index_count'].astype(int)
    #refined_list.set_index(['index_count'])
    refined_list['index_value'] = refined_list.index
    #refined_list.DateTime.tolist()
    #refined_list.dtypes
    refined_list = refined_list.set_index(['index_count','index_value'])

    return refined_list

In [5]:
final_table(weather_file_above_threshold)

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           200          1991-07-20  20.2884    30.1610  36.4549
            201          1991-07-21  20.9882    30.1809  35.8746
            203          1991-07-23  22.2694    30.1111  35.5850
1           918          1993-07-07  22.2687    29.8566  34.9479
            919          1993-07-08  21.7611    31.6063  36.3469
            920          1993-07-09  19.3806    32.3365  37.4773
            921          1993-07-10  20.2286    31.6914  37.5471
2           1284         1994-07-08  22.5519    29.3566  33.6633
            1285         1994-07-09  22.2383    28.8062  33.3326
3           1655         1995-07-14  20.7647    29.6513  36.2968
            1656         1995-07-15  22.6235    31.7269  38.2673
4           1667         1995-07-26  22.4758    28.9965  32.6266
            1668         1995-07-27  21.7881    29.8467  33.1371
            1669         1995-07-28  22.2804    29.1561  31.9466
            1670         1995-07-29  21.8158    30.1614  33.8566
5           2387         1997-07-15  20.6909    29.8889  35.7787
            2388         1997-07-16  21.3333    29.8587  34.2687
            2389         1997-07-17  19.5592    30.1135  34.5879
6           3106         1999-07-04  22.5213    30.8131  36.1088
            3107         1999-07-05  22.5430    32.7128  37.9979
            3108         1999-07-06  21.7924    31.5378  36.9685
7           3871         2001-08-07  20.5326    29.3802  35.5342
            3872         2001-08-08  21.1636    30.4502  35.7546
            3873         2001-08-09  20.7511    31.1055  36.6652
            3874         2001-08-10  22.7621    29.9905  33.8953
8           4201         2002-07-03  21.1851    31.2508  36.7110
            4202         2002-07-04  20.5538    31.5305  36.5411
9           5338         2005-08-13  22.8777    30.8525  35.2331
            5339         2005-08-14  22.8510    31.1872  35.0923
10          5691         2006-08-01  21.4175    29.7827  35.5960
...                             ...      ...        ...      ...
14          8223         2013-07-07  19.6039    30.9673  37.8262
15          8230         2013-07-14  19.6169    30.1955  36.8785
            8231         2013-07-15  19.7339    30.9795  37.6445
16          8234         2013-07-18  19.6346    31.4111  38.7649
            8235         2013-07-19  20.4954    32.1772  39.0952
            8236         2013-07-20  20.7304    31.4933  36.9967
17          8965         2015-07-19  18.4141    31.0241  34.4315
            8966         2015-07-20  22.1983    30.4190  34.3315
18          8974         2015-07-28  20.6575    29.5592  34.2316
            8975         2015-07-29  20.7373    30.3287  34.6812
19          9353         2016-08-10  21.7220    28.6762  30.8089
            9354         2016-08-11  23.0205    29.1112  34.0089
            9355         2016-08-12  23.4715    30.5362  34.6089
            9356         2016-08-13  23.9413    31.8512  35.6589
            9357         2016-08-14  22.2425    30.2562  34.8889
            9358         2016-08-15  21.5992    29.3762  33.0289
20          9696         2017-07-19  21.3950    29.3367  33.5270
            9697         2017-07-20  20.7310    29.7537  34.8590
            9698         2017-07-21  20.7552    29.5747  33.7770
21          10043        2018-07-01  20.8945    30.3668  35.5044
            10044        2018-07-02  21.9748    30.1768  34.8174
            10045        2018-07-03  23.0943    28.9478  33.0745
22          10079        2018-08-06  21.9798    29.2395  33.4449
            10080        2018-08-07  23.1125    27.7245  32.0139
            10081        2018-08-08  22.7500    28.0130  32.3509
23          10101        2018-08-28  22.3603    30.3640  34.6349
            10102        2018-08-29  22.5407    29.9880  33.9239
24          10107        2018-09-03  21.5176    28.7953  32.8329
            10109        2018-09-05  21.7569    28.7958  32.2679
            10110        2018-09-06  22.3709    28.8408  34.1399

                         Apparent temp
index_count index_value
0           200              33.623807
            201              34.085534
            203              34.864104
1           918              34.610654
            919              36.007908
            920              35.235278
            921              35.107954
2           1284             34.307860
            1285             33.545855
3           1655             33.416336
            1656             36.713427
4           1667             33.897493
            1668             34.276856
            1669             33.922332
            1670             34.608147
5           2387             33.605701
            2388             33.988726
            2389             33.132022
6           3106             35.734518
            3107             37.637782
            3108             35.960676
7           3871             33.000210
            3872             34.466338
            3873             34.853172
            3874             35.083689
8           4201             35.276065
            4202             35.150935
9           5338             36.021239
            5339             36.335250
10          5691             33.968256
...                                ...
14          8223             34.007483
15          8230             33.248115
            8231             34.097853
16          8234             34.467051
            8235             35.757077
            8236             35.225507
17          8965             33.371865
            8966             35.121783
18          8974             33.256849
            8975             34.072273
19          9353             33.069376
            9354             34.390667
            9355             36.127926
            9356             37.775836
            9357             34.990014
            9358             33.683782
20          9696             33.510194
            9697             33.496726
            9698             33.334160
21          10043            34.210275
            10044            34.729984
            10045            34.280318
22          10079            33.801671
            10080            33.077224
            10081            33.109628
23          10101            35.177556
            10102            34.927744
24          10107            33.052537
            10109            33.211474
            10110            33.670750

[72 rows x 5 columns]

In [6]:
index_list = list(weather_file_above_threshold.index)
len(index_list)

97

## Grouping the consecutive days on basis of date with 1 day gap tolerance

In [7]:

dicts = {}
index_list = list(weather_file_above_threshold.index)
consecutive_days_list_case = []
non_consecutive_days_list = []
for i in range(len(index_list) - 1):
#    print (i)
    if (index_list[i+1] - index_list[i] <= 2) | (index_list[i] - index_list[i-1] <= 2):
         consecutive_days_list_case.append(index_list[i])
    else:
        non_consecutive_days_list.append(i)

            
#data = [1, 4, 5, 6, 10, 15, 16, 17, 18, 22, 25, 26, 27, 28]
spl = [0]+[i for i in range(1,len(consecutive_days_list_case)) if consecutive_days_list_case[i]-consecutive_days_list_case[i-1]>2]+[None]


heatwave_days_cluster =([consecutive_days_list_case[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]])            
heatwave_days_cluster           
        
#        print (x[i])
#    else:
#        print ('--------------')

[[200, 201, 203],
 [918, 919, 920, 921],
 [1284, 1285],
 [1655, 1656],
 [1667, 1668, 1669, 1670],
 [2387, 2388, 2389],
 [3106, 3107, 3108],
 [3871, 3872, 3873, 3874],
 [4201, 4202],
 [5338, 5339],
 [5691, 5692, 5693],
 [7125, 7126, 7127],
 [7136, 7137],
 [7506, 7507, 7508, 7509],
 [8222, 8223],
 [8230, 8231],
 [8234, 8235, 8236],
 [8965, 8966],
 [8974, 8975],
 [9353, 9354, 9355, 9356, 9357, 9358],
 [9696, 9697, 9698],
 [10043, 10044, 10045],
 [10079, 10080, 10081],
 [10101, 10102],
 [10107, 10109]]

In [8]:
refined_list = weather_file_above_threshold.drop(weather_file_above_threshold.index[non_consecutive_days_list])
refined_list.drop(10110, inplace = True)
refined_list.dtypes

DateTime          object
DPT              float64
Mean Temp        float64
MaxTemp          float64
Apparent temp    float64
dtype: object

In [9]:
heatwave_days_list = []
for i in heatwave_days_cluster:
    for m in i:
        heatwave_days_list.append(m)   
heatwave_days_list

[200,
 201,
 203,
 918,
 919,
 920,
 921,
 1284,
 1285,
 1655,
 1656,
 1667,
 1668,
 1669,
 1670,
 2387,
 2388,
 2389,
 3106,
 3107,
 3108,
 3871,
 3872,
 3873,
 3874,
 4201,
 4202,
 5338,
 5339,
 5691,
 5692,
 5693,
 7125,
 7126,
 7127,
 7136,
 7137,
 7506,
 7507,
 7508,
 7509,
 8222,
 8223,
 8230,
 8231,
 8234,
 8235,
 8236,
 8965,
 8966,
 8974,
 8975,
 9353,
 9354,
 9355,
 9356,
 9357,
 9358,
 9696,
 9697,
 9698,
 10043,
 10044,
 10045,
 10079,
 10080,
 10081,
 10101,
 10102,
 10107,
 10109]

## Grouping the Heatwave days

In [10]:
#data = [1, 4, 5, 6, 10, 15, 16, 17, 18, 22, 25, 26, 27, 28]
#spl = [0]+[i for i in range(1,len(n)) if n[i]-n[i-1]>2]+[None]
groups = [consecutive_days_list_case[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]]
#groups
dicts = {}
for i in range(len(groups)):
    dicts[i] = groups[i]
print(dicts)

{0: [200, 201, 203], 1: [918, 919, 920, 921], 2: [1284, 1285], 3: [1655, 1656], 4: [1667, 1668, 1669, 1670], 5: [2387, 2388, 2389], 6: [3106, 3107, 3108], 7: [3871, 3872, 3873, 3874], 8: [4201, 4202], 9: [5338, 5339], 10: [5691, 5692, 5693], 11: [7125, 7126, 7127], 12: [7136, 7137], 13: [7506, 7507, 7508, 7509], 14: [8222, 8223], 15: [8230, 8231], 16: [8234, 8235, 8236], 17: [8965, 8966], 18: [8974, 8975], 19: [9353, 9354, 9355, 9356, 9357, 9358], 20: [9696, 9697, 9698], 21: [10043, 10044, 10045], 22: [10079, 10080, 10081], 23: [10101, 10102], 24: [10107, 10109]}

In [11]:
weather_data_2 = weather_file_above_threshold
df_weather = pd.DataFrame.from_dict(dicts, orient = 'index')
#df_weather
new_df_weather = df_weather.stack().reset_index(level=1, drop=True).to_frame('ttt')
new_df_weather['index_count'] = new_df_weather.index
#grouped = new_df_weather.groupby('index_count')
#for name in grouped:
#    print (name)
#   print (group)

#weather_data_2
new_df_weather.dtypes
new_df_weather['ttt'] = new_df_weather['ttt'].astype(int)
new_df_weather = new_df_weather.set_index('ttt')
new_df_weather

       index_count
ttt
200              0
201              0
203              0
918              1
919              1
920              1
921              1
1284             2
1285             2
1655             3
1656             3
1667             4
1668             4
1669             4
1670             4
2387             5
2388             5
2389             5
3106             6
3107             6
3108             6
3871             7
3872             7
3873             7
3874             7
4201             8
4202             8
5338             9
5339             9
5691            10
...            ...
8222            14
8223            14
8230            15
8231            15
8234            16
8235            16
8236            16
8965            17
8966            17
8974            18
8975            18
9353            19
9354            19
9355            19
9356            19
9357            19
9358            19
9696            20
9697            20
9698            20
10043           21
10044           21
10045           21
10079           22
10080           22
10081           22
10101           23
10102           23
10107           24
10109           24

[71 rows x 1 columns]

# Final heat wave data

In [12]:
#refined_lists = refined_list.join(new_df_weather)

refined_list['index_count'] = new_df_weather['index_count']
refined_list['index_count'] = refined_list['index_count'].astype(int)
#refined_list.set_index(['index_count'])
refined_list['index_value'] = refined_list.index
#refined_list.DateTime.tolist()
#refined_list.dtypes
refined_list = refined_list.set_index(['index_count','index_value'])

refined_list

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           200          1991-07-20  20.2884    30.1610  36.4549
            201          1991-07-21  20.9882    30.1809  35.8746
            203          1991-07-23  22.2694    30.1111  35.5850
1           918          1993-07-07  22.2687    29.8566  34.9479
            919          1993-07-08  21.7611    31.6063  36.3469
            920          1993-07-09  19.3806    32.3365  37.4773
            921          1993-07-10  20.2286    31.6914  37.5471
2           1284         1994-07-08  22.5519    29.3566  33.6633
            1285         1994-07-09  22.2383    28.8062  33.3326
3           1655         1995-07-14  20.7647    29.6513  36.2968
            1656         1995-07-15  22.6235    31.7269  38.2673
4           1667         1995-07-26  22.4758    28.9965  32.6266
            1668         1995-07-27  21.7881    29.8467  33.1371
            1669         1995-07-28  22.2804    29.1561  31.9466
            1670         1995-07-29  21.8158    30.1614  33.8566
5           2387         1997-07-15  20.6909    29.8889  35.7787
            2388         1997-07-16  21.3333    29.8587  34.2687
            2389         1997-07-17  19.5592    30.1135  34.5879
6           3106         1999-07-04  22.5213    30.8131  36.1088
            3107         1999-07-05  22.5430    32.7128  37.9979
            3108         1999-07-06  21.7924    31.5378  36.9685
7           3871         2001-08-07  20.5326    29.3802  35.5342
            3872         2001-08-08  21.1636    30.4502  35.7546
            3873         2001-08-09  20.7511    31.1055  36.6652
            3874         2001-08-10  22.7621    29.9905  33.8953
8           4201         2002-07-03  21.1851    31.2508  36.7110
            4202         2002-07-04  20.5538    31.5305  36.5411
9           5338         2005-08-13  22.8777    30.8525  35.2331
            5339         2005-08-14  22.8510    31.1872  35.0923
10          5691         2006-08-01  21.4175    29.7827  35.5960
...                             ...      ...        ...      ...
14          8222         2013-07-06  19.8732    30.7530  37.1491
            8223         2013-07-07  19.6039    30.9673  37.8262
15          8230         2013-07-14  19.6169    30.1955  36.8785
            8231         2013-07-15  19.7339    30.9795  37.6445
16          8234         2013-07-18  19.6346    31.4111  38.7649
            8235         2013-07-19  20.4954    32.1772  39.0952
            8236         2013-07-20  20.7304    31.4933  36.9967
17          8965         2015-07-19  18.4141    31.0241  34.4315
            8966         2015-07-20  22.1983    30.4190  34.3315
18          8974         2015-07-28  20.6575    29.5592  34.2316
            8975         2015-07-29  20.7373    30.3287  34.6812
19          9353         2016-08-10  21.7220    28.6762  30.8089
            9354         2016-08-11  23.0205    29.1112  34.0089
            9355         2016-08-12  23.4715    30.5362  34.6089
            9356         2016-08-13  23.9413    31.8512  35.6589
            9357         2016-08-14  22.2425    30.2562  34.8889
            9358         2016-08-15  21.5992    29.3762  33.0289
20          9696         2017-07-19  21.3950    29.3367  33.5270
            9697         2017-07-20  20.7310    29.7537  34.8590
            9698         2017-07-21  20.7552    29.5747  33.7770
21          10043        2018-07-01  20.8945    30.3668  35.5044
            10044        2018-07-02  21.9748    30.1768  34.8174
            10045        2018-07-03  23.0943    28.9478  33.0745
22          10079        2018-08-06  21.9798    29.2395  33.4449
            10080        2018-08-07  23.1125    27.7245  32.0139
            10081        2018-08-08  22.7500    28.0130  32.3509
23          10101        2018-08-28  22.3603    30.3640  34.6349
            10102        2018-08-29  22.5407    29.9880  33.9239
24          10107        2018-09-03  21.5176    28.7953  32.8329
            10109        2018-09-05  21.7569    28.7958  32.2679

                         Apparent temp
index_count index_value
0           200              33.623807
            201              34.085534
            203              34.864104
1           918              34.610654
            919              36.007908
            920              35.235278
            921              35.107954
2           1284             34.307860
            1285             33.545855
3           1655             33.416336
            1656             36.713427
4           1667             33.897493
            1668             34.276856
            1669             33.922332
            1670             34.608147
5           2387             33.605701
            2388             33.988726
            2389             33.132022
6           3106             35.734518
            3107             37.637782
            3108             35.960676
7           3871             33.000210
            3872             34.466338
            3873             34.853172
            3874             35.083689
8           4201             35.276065
            4202             35.150935
9           5338             36.021239
            5339             36.335250
10          5691             33.968256
...                                ...
14          8222             33.957126
            8223             34.007483
15          8230             33.248115
            8231             34.097853
16          8234             34.467051
            8235             35.757077
            8236             35.225507
17          8965             33.371865
            8966             35.121783
18          8974             33.256849
            8975             34.072273
19          9353             33.069376
            9354             34.390667
            9355             36.127926
            9356             37.775836
            9357             34.990014
            9358             33.683782
20          9696             33.510194
            9697             33.496726
            9698             33.334160
21          10043            34.210275
            10044            34.729984
            10045            34.280318
22          10079            33.801671
            10080            33.077224
            10081            33.109628
23          10101            35.177556
            10102            34.927744
24          10107            33.052537
            10109            33.211474

[71 rows x 5 columns]

# Control Days

In [13]:
ctrl_days = []
#len(groups[2])
#momo.str.len()
for i in heatwave_days_cluster:
    days = i[0] - len(i)
    #print (days_b)
    k_b = range(days,i[0])
    for m in k_b:
        if m in heatwave_days_list:
            print('overlap at ',m)
            continue
            
            
        ctrl_days.append(m)
print (ctrl_days)

overlap at  8231
[197, 198, 199, 914, 915, 916, 917, 1282, 1283, 1653, 1654, 1663, 1664, 1665, 1666, 2384, 2385, 2386, 3103, 3104, 3105, 3867, 3868, 3869, 3870, 4199, 4200, 5336, 5337, 5688, 5689, 5690, 7122, 7123, 7124, 7134, 7135, 7502, 7503, 7504, 7505, 8220, 8221, 8228, 8229, 8232, 8233, 8963, 8964, 8972, 8973, 9347, 9348, 9349, 9350, 9351, 9352, 9693, 9694, 9695, 10040, 10041, 10042, 10076, 10077, 10078, 10099, 10100, 10105, 10106]

In [14]:
weather_data_ctrl_immediate_days = weather_data_file.loc[ctrl_days]
#weather_data_ctrl_immediate_days

In [15]:
dicts = {}
index_list = list(weather_data_ctrl_immediate_days.index)
consecutive_days_list = []
non_consecutive_days_list = []
for i in range(len(index_list)):
    try:
        if (index_list[i+1] - index_list[i] <= 2) | (index_list[i] - index_list[i-1] <= 2):
             consecutive_days_list.append(index_list[i])
        else:
            non_consecutive_days_list.append(i)
    except:
        consecutive_days_list.append(index_list[i])

#data = [1, 4, 5, 6, 10, 15, 16, 17, 18, 22, 25, 26, 27, 28]
spl = [0]+[i for i in range(1,len(consecutive_days_list)) if consecutive_days_list[i]-consecutive_days_list[i-1]>2]+[None]


heatwave_days_cluster_control =([consecutive_days_list[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]])            
(heatwave_days_cluster_control)           
        
#        print (x[i])
#    else:
#        print ('--------------')
    

groups_control = [consecutive_days_list[b:e] for (b, e) in [(spl[i-1],spl[i]) for i in range(1,len(spl))]]
#groups
dicts_control = {}
for i in range(len(groups_control)):
    dicts_control[i] = groups_control[i]
#print(dicts_control) 

weather_data_control = weather_data_ctrl_immediate_days
df_weather = pd.DataFrame.from_dict(dicts_control, orient = 'index')
#df_weather
new_df_weather_control = df_weather.stack().reset_index(level=1, drop=True).to_frame('ttt')
new_df_weather_control['index_count'] = new_df_weather_control.index
#grouped = new_df_weather.groupby('index_count')
#for name in grouped:
#    print (name)
#   print (group)

#weather_data_2
new_df_weather_control.dtypes
new_df_weather_control['ttt'] = new_df_weather_control['ttt'].astype(int)
new_df_weather_control = new_df_weather_control.set_index('ttt')
new_df_weather_control

       index_count
ttt
197              0
198              0
199              0
914              1
915              1
916              1
917              1
1282             2
1283             2
1653             3
1654             3
1663             4
1664             4
1665             4
1666             4
2384             5
2385             5
2386             5
3103             6
3104             6
3105             6
3867             7
3868             7
3869             7
3870             7
4199             8
4200             8
5336             9
5337             9
5688            10
...            ...
7505            13
8220            14
8221            14
8228            15
8229            15
8232            16
8233            16
8963            17
8964            17
8972            18
8973            18
9347            19
9348            19
9349            19
9350            19
9351            19
9352            19
9693            20
9694            20
9695            20
10040           21
10041           21
10042           21
10076           22
10077           22
10078           22
10099           23
10100           23
10105           24
10106           24

[70 rows x 1 columns]

In [16]:
#weather_data_ctrl_immediate_days.drop(10107, inplace = True)
weather_data_ctrl_immediate_days
weather_data_ctrl_immediate_days['index_value'] = weather_data_ctrl_immediate_days.index
weather_data_ctrl_immediate_days['index_count'] = new_df_weather_control['index_count']
weather_data_ctrl_immediate_days.set_index(['index_count','index_value'])
#weather_data_ctrl_immediate_days

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           197          1991-07-17  17.0134    25.9707  32.8747
            198          1991-07-18  18.5805    27.7155  34.5947
            199          1991-07-19  21.0015    28.6158  34.1048
1           914          1993-07-03  18.6796    24.4466  30.3073
            915          1993-07-04  19.2947    29.3418  33.6079
            916          1993-07-05  17.1997    27.0365  31.5473
            917          1993-07-06  19.8462    27.1067  33.4175
2           1282         1994-07-06  21.6105    27.8016  33.3728
            1283         1994-07-07  21.1058    28.9021  34.3335
3           1653         1995-07-12  17.4819    24.7512  29.0466
            1654         1995-07-13  19.0447    26.2368  32.5672
4           1663         1995-07-22  19.9964    27.0815  29.3766
            1664         1995-07-23  21.4925    27.4265  30.9676
            1665         1995-07-24  20.0966    27.8320  31.6376
            1666         1995-07-25  21.9616    27.9970  30.9874
5           2384         1997-07-12  13.5190    23.9886  30.3683
            2385         1997-07-13  16.3526    26.0637  32.7586
            2386         1997-07-14  18.0509    27.7534  34.1776
6           3103         1999-07-01  19.7055    24.7881  26.6587
            3104         1999-07-02  20.2746    26.9132  29.8883
            3105         1999-07-03  20.8278    28.1075  32.2677
7           3867         2001-08-03  17.6178    24.6601  31.0144
            3868         2001-08-04  19.6287    25.8505  29.9549
            3869         2001-08-05  20.5761    26.7205  30.7051
            3870         2001-08-06  21.2436    28.5052  33.8444
8           4199         2002-07-01  17.1751    26.1805  31.0305
            4200         2002-07-02  20.0481    28.3609  34.8814
9           5336         2005-08-11  19.8854    29.2124  34.2227
            5337         2005-08-12  20.1675    29.1624  33.9523
10          5688         2006-07-29  19.3295    27.0917  32.6882
...                             ...      ...        ...      ...
13          7505         2011-07-20  20.6268    28.1176  33.1215
14          8220         2013-07-04  19.4297    29.2288  35.8140
            8221         2013-07-05  19.6030    29.7583  36.6969
15          8228         2013-07-12  17.7960    26.0241  28.7283
            8229         2013-07-13  18.8104    26.5855  30.4026
16          8232         2013-07-16  18.2833    30.2841  37.0780
            8233         2013-07-17  17.8691    30.4163  36.4924
17          8963         2015-07-17  15.6228    24.4486  26.8306
            8964         2015-07-18  19.8504    26.1887  29.7111
18          8972         2015-07-26  17.7677    27.2038  31.3511
            8973         2015-07-27  19.4714    26.6787  29.9109
19          9347         2016-08-04  16.8534    24.1062  27.6489
            9348         2016-08-05  18.5832    26.0612  28.6989
            9349         2016-08-06  21.0484    26.1912  30.7989
            9350         2016-08-07  15.4879    26.1412  30.4789
            9351         2016-08-08  14.0293    25.6262  29.7089
            9352         2016-08-09  15.4633    27.5762  30.7389
20          9693         2017-07-16  17.8753    25.9932  29.8050
            9694         2017-07-17  20.2978    26.4332  29.6120
            9695         2017-07-18  21.0008    27.4957  30.7230
21          10040        2018-06-28  18.8445    25.2229  28.8354
            10041        2018-06-29  18.6548    27.4629  32.8084
            10042        2018-06-30  18.6563    29.3588  33.9344
22          10076        2018-08-03  21.8652    26.3780  29.2149
            10077        2018-08-04  20.2806    26.5840  30.7289
            10078        2018-08-05  20.8589    28.8190  32.9249
23          10099        2018-08-26  19.3282    25.3190  28.7739
            10100        2018-08-27  21.3633    28.0335  31.5979
24          10105        2018-09-01  17.9422    23.0238  25.8699
            10106        2018-09-02  18.7967    25.1263  27.9879

                         Apparent temp
index_count index_value
0           197              27.589549
            198              30.177302
            199              32.538369
1           914              26.984510
            915              32.207717
            916              28.746475
            917              30.316296
2           1282             32.126100
            1283             32.890146
3           1653             26.624630
            1654             28.974698
4           1663             30.382808
            1664             31.675433
            1665             31.190270
            1666             32.554390
5           2384             23.986948
            2385             27.344653
            2386             29.918155
6           3103             27.926464
            3104             30.386930
            3105             31.921953
7           3867             26.607059
            3868             28.936271
            3869             30.383828
            3870             32.584914
8           4199             27.882673
            4200             31.686207
9           5336             32.433191
            5337             32.556365
10          5688             29.991682
...                                ...
13          7505             31.804507
14          8220             32.175380
            8221             32.805198
15          8228             28.059429
            8229             29.185604
16          8232             32.562865
            8233             32.465165
17          8963             25.382208
            8964             29.406355
18          8972             29.216652
            8973             29.665400
19          9347             25.653330
            9348             28.534463
            9349             30.158490
            9350             27.000441
            9351             25.829808
            9352             28.415182
20          9693             28.071994
            9694             29.924211
            9695             31.424540
21          10040            27.850825
            10041            29.968547
            10042            31.853927
22          10076            30.880463
            10077            30.063428
            10078            32.649020
23          10099            28.228850
            10100            32.194075
24          10105            25.157072
            10106            27.727276

[70 rows x 5 columns]

# control data (7 days before heat_wave)

In [17]:
control_days_list_7 = []
for i in heatwave_days_cluster:
    m =  i[0] - 7
    k = range(m,i[0])
    for days in k:
        if days in heatwave_days_list:
            print ('overlap at ',days)
            continue
        control_days_list_7.append(days)
print (control_days_list_7)

overlap at  8223
overlap at  8230
overlap at  8231
overlap at  10101
overlap at  10102
[193, 194, 195, 196, 197, 198, 199, 911, 912, 913, 914, 915, 916, 917, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1648, 1649, 1650, 1651, 1652, 1653, 1654, 1660, 1661, 1662, 1663, 1664, 1665, 1666, 2380, 2381, 2382, 2383, 2384, 2385, 2386, 3099, 3100, 3101, 3102, 3103, 3104, 3105, 3864, 3865, 3866, 3867, 3868, 3869, 3870, 4194, 4195, 4196, 4197, 4198, 4199, 4200, 5331, 5332, 5333, 5334, 5335, 5336, 5337, 5684, 5685, 5686, 5687, 5688, 5689, 5690, 7118, 7119, 7120, 7121, 7122, 7123, 7124, 7129, 7130, 7131, 7132, 7133, 7134, 7135, 7499, 7500, 7501, 7502, 7503, 7504, 7505, 8215, 8216, 8217, 8218, 8219, 8220, 8221, 8224, 8225, 8226, 8227, 8228, 8229, 8227, 8228, 8229, 8232, 8233, 8958, 8959, 8960, 8961, 8962, 8963, 8964, 8967, 8968, 8969, 8970, 8971, 8972, 8973, 9346, 9347, 9348, 9349, 9350, 9351, 9352, 9689, 9690, 9691, 9692, 9693, 9694, 9695, 10036, 10037, 10038, 10039, 10040, 10041, 10042, 10072, 10073, 10074, 10075, 10076, 10077, 10078, 10094, 10095, 10096, 10097, 10098, 10099, 10100, 10100, 10103, 10104, 10105, 10106]

In [18]:
weather_data_ctrl_immediate_days_7 = weather_data_file.loc[control_days_list_7]

weather_data_ctrl_immediate_days_7

         DateTime      DPT  Mean Temp  MaxTemp  Apparent temp
193    1991-07-13  19.6937    25.1258  28.3748      28.255025
194    1991-07-14  16.7824    25.7308  28.7651      27.231644
195    1991-07-15  13.7313    25.6411  30.4249      25.718047
196    1991-07-16  14.6237    24.9264  30.8755      25.394786
197    1991-07-17  17.0134    25.9707  32.8747      27.589549
198    1991-07-18  18.5805    27.7155  34.5947      30.177302
199    1991-07-19  21.0015    28.6158  34.1048      32.538369
911    1993-06-30  15.9377    26.0314  29.4373      27.107569
912    1993-07-01  15.0508    23.9365  28.6070      24.604738
913    1993-07-02  15.3641    19.9864  21.4877      20.824132
914    1993-07-03  18.6796    24.4466  30.3073      26.984510
915    1993-07-04  19.2947    29.3418  33.6079      32.207717
916    1993-07-05  17.1997    27.0365  31.5473      28.746475
917    1993-07-06  19.8462    27.1067  33.4175      30.316296
1277   1994-07-01  17.8006    24.5866  28.7229      26.633059
1278   1994-07-02  19.5143    25.6269  31.1836      28.645500
1279   1994-07-03  18.9709    26.4914  30.9925      29.184846
1280   1994-07-04  17.5349    24.1821  28.6437      26.087340
1281   1994-07-05  18.6795    23.9067  29.7427      26.447793
1282   1994-07-06  21.6105    27.8016  33.3728      32.126100
1283   1994-07-07  21.1058    28.9021  34.3335      32.890146
1648   1995-07-07  18.5917    24.4520  27.6077      26.939753
1649   1995-07-08  17.2483    24.4171  28.7277      26.168406
1650   1995-07-09  11.7314    20.2165  25.0265      19.546875
1651   1995-07-10  14.3693    22.0614  27.2269      22.434126
1652   1995-07-11  16.6597    24.4314  27.4470      25.877259
1653   1995-07-12  17.4819    24.7512  29.0466      26.624630
1654   1995-07-13  19.0447    26.2368  32.5672      28.974698
1660   1995-07-19  15.7605    25.5718  30.0071      26.564788
1661   1995-07-20  16.6783    25.6365  30.7970      27.084616
...           ...      ...        ...      ...            ...
9692   2017-07-15  18.4747    24.8372  29.2680      27.256289
9693   2017-07-16  17.8753    25.9932  29.8050      28.071994
9694   2017-07-17  20.2978    26.4332  29.6120      29.924211
9695   2017-07-18  21.0008    27.4957  30.7230      31.424540
10036  2018-06-24  18.2361    24.6469  29.4624      26.933115
10037  2018-06-25  12.6763    22.4039  27.7314      22.074012
10038  2018-06-26  13.0039    21.7174  25.0064      21.520347
10039  2018-06-27  16.6040    21.8769  23.0474      23.309739
10040  2018-06-28  18.8445    25.2229  28.8354      27.850825
10041  2018-06-29  18.6548    27.4629  32.8084      29.968547
10042  2018-06-30  18.6563    29.3588  33.9344      31.853927
10072  2018-07-30  16.8643    23.2323  26.2295      24.790297
10073  2018-07-31  19.0037    25.0810  27.0819      27.801965
10074  2018-08-01  21.7129    27.1510  30.0398      31.547279
10075  2018-08-02  22.3598    27.4515  30.4559      32.282189
10076  2018-08-03  21.8652    26.3780  29.2149      30.880463
10077  2018-08-04  20.2806    26.5840  30.7289      30.063428
10078  2018-08-05  20.8589    28.8190  32.9249      32.649020
10094  2018-08-21  19.2817    23.4105  25.1669      26.304332
10095  2018-08-22  18.6661    24.2805  28.9239      26.811693
10096  2018-08-23  13.0033    22.2140  26.0739      22.013729
10097  2018-08-24  14.6072    23.8280  28.2319      24.295597
10098  2018-08-25  17.7442    23.2320  26.6609      25.255914
10099  2018-08-26  19.3282    25.3190  28.7739      28.228850
10100  2018-08-27  21.3633    28.0335  31.5979      32.194075
10100  2018-08-27  21.3633    28.0335  31.5979      32.194075
10103  2018-08-30  20.4944    27.6785  32.0149      31.284742
10104  2018-08-31  19.0452    22.6697  24.1869      25.429292
10105  2018-09-01  17.9422    23.0238  25.8699      25.157072
10106  2018-09-02  18.7967    25.1263  27.9879      27.727276

[170 rows x 5 columns]

In [19]:
dicts_7 = {}
index_list_7 = list(weather_data_ctrl_immediate_days_7.index)
consecutive_days_list_7 = []
non_consecutive_days_list_7 = []
for i in range(len(index_list_7)):
#    print (i)
    try:
        if (index_list_7[i+1] - index_list_7[i] <= 2) | (index_list_7[i] - index_list_7[i-1] <= 2):
             consecutive_days_list_7.append(index_list_7[i])
        else:
            non_consecutive_days_list_7.append(i)
    except:
        consecutive_days_list_7.append(index_list_7[i])

            
#data = [1, 4, 5, 6, 10, 15, 16, 17, 18, 22, 25, 26, 27, 28]
spl_7 = [0]+[i for i in range(1,len(consecutive_days_list_7)) if consecutive_days_list_7[i]-consecutive_days_list_7[i-1]>2]+[None]


heatwave_days_cluster_control_7 =([consecutive_days_list_7[b:e] for (b, e) in [(spl_7[i-1],spl_7[i]) for i in range(1,len(spl_7))]])            
(heatwave_days_cluster_control_7)           
        
#        print (x[i])
#    else:
#        print ('--------------')
    

groups_control_7 = [consecutive_days_list_7[b:e] for (b, e) in [(spl_7[i-1],spl_7[i]) for i in range(1,len(spl_7))]]
#groups
dicts_control_7 = {}
for i in range(len(groups_control_7)):
    dicts_control_7[i] = groups_control_7[i]
#print(dicts_control) 

weather_data_control_7 = weather_data_ctrl_immediate_days_7
df_weather_7 = pd.DataFrame.from_dict(dicts_control_7, orient = 'index')
#df_weather
new_df_weather_control_7 = df_weather_7.stack().reset_index(level=1, drop=True).to_frame('ttt_7')
new_df_weather_control_7['index_count'] = new_df_weather_control_7.index
#grouped = new_df_weather.groupby('index_count')
#for name in grouped:
#    print (name)
#   print (group)

#weather_data_2
new_df_weather_control_7.dtypes
new_df_weather_control_7['ttt_7'] = new_df_weather_control_7['ttt_7'].astype(int)
new_df_weather_control_7 = new_df_weather_control_7.set_index('ttt_7')
new_df_weather_control_7

       index_count
ttt_7
193              0
194              0
195              0
196              0
197              0
198              0
199              0
911              1
912              1
913              1
914              1
915              1
916              1
917              1
1277             2
1278             2
1279             2
1280             2
1281             2
1282             2
1283             2
1648             3
1649             3
1650             3
1651             3
1652             3
1653             3
1654             3
1660             4
1661             4
...            ...
9692            20
9693            20
9694            20
9695            20
10036           21
10037           21
10038           21
10039           21
10040           21
10041           21
10042           21
10072           22
10073           22
10074           22
10075           22
10076           22
10077           22
10078           22
10094           23
10095           23
10096           23
10097           23
10098           23
10099           23
10100           23
10100           23
10103           24
10104           24
10105           24
10106           24

[170 rows x 1 columns]

In [20]:
#weather_data_ctrl_immediate_days_7.drop(10106, inplace = True)

In [21]:
#weather_data_ctrl_immediate_days.drop(10106, inplace = True)
weather_data_ctrl_immediate_days_7
weather_data_ctrl_immediate_days_7['index_value'] = weather_data_ctrl_immediate_days_7.index
weather_data_ctrl_immediate_days_7['index_count'] = new_df_weather_control_7['index_count']
weather_data_ctrl_immediate_days_7 = weather_data_ctrl_immediate_days_7.set_index(['index_count','index_value'])
weather_data_ctrl_immediate_days_7

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           193          1991-07-13  19.6937    25.1258  28.3748
            194          1991-07-14  16.7824    25.7308  28.7651
            195          1991-07-15  13.7313    25.6411  30.4249
            196          1991-07-16  14.6237    24.9264  30.8755
            197          1991-07-17  17.0134    25.9707  32.8747
            198          1991-07-18  18.5805    27.7155  34.5947
            199          1991-07-19  21.0015    28.6158  34.1048
1           911          1993-06-30  15.9377    26.0314  29.4373
            912          1993-07-01  15.0508    23.9365  28.6070
            913          1993-07-02  15.3641    19.9864  21.4877
            914          1993-07-03  18.6796    24.4466  30.3073
            915          1993-07-04  19.2947    29.3418  33.6079
            916          1993-07-05  17.1997    27.0365  31.5473
            917          1993-07-06  19.8462    27.1067  33.4175
2           1277         1994-07-01  17.8006    24.5866  28.7229
            1278         1994-07-02  19.5143    25.6269  31.1836
            1279         1994-07-03  18.9709    26.4914  30.9925
            1280         1994-07-04  17.5349    24.1821  28.6437
            1281         1994-07-05  18.6795    23.9067  29.7427
            1282         1994-07-06  21.6105    27.8016  33.3728
            1283         1994-07-07  21.1058    28.9021  34.3335
3           1648         1995-07-07  18.5917    24.4520  27.6077
            1649         1995-07-08  17.2483    24.4171  28.7277
            1650         1995-07-09  11.7314    20.2165  25.0265
            1651         1995-07-10  14.3693    22.0614  27.2269
            1652         1995-07-11  16.6597    24.4314  27.4470
            1653         1995-07-12  17.4819    24.7512  29.0466
            1654         1995-07-13  19.0447    26.2368  32.5672
4           1660         1995-07-19  15.7605    25.5718  30.0071
            1661         1995-07-20  16.6783    25.6365  30.7970
...                             ...      ...        ...      ...
20          9692         2017-07-15  18.4747    24.8372  29.2680
            9693         2017-07-16  17.8753    25.9932  29.8050
            9694         2017-07-17  20.2978    26.4332  29.6120
            9695         2017-07-18  21.0008    27.4957  30.7230
21          10036        2018-06-24  18.2361    24.6469  29.4624
            10037        2018-06-25  12.6763    22.4039  27.7314
            10038        2018-06-26  13.0039    21.7174  25.0064
            10039        2018-06-27  16.6040    21.8769  23.0474
            10040        2018-06-28  18.8445    25.2229  28.8354
            10041        2018-06-29  18.6548    27.4629  32.8084
            10042        2018-06-30  18.6563    29.3588  33.9344
22          10072        2018-07-30  16.8643    23.2323  26.2295
            10073        2018-07-31  19.0037    25.0810  27.0819
            10074        2018-08-01  21.7129    27.1510  30.0398
            10075        2018-08-02  22.3598    27.4515  30.4559
            10076        2018-08-03  21.8652    26.3780  29.2149
            10077        2018-08-04  20.2806    26.5840  30.7289
            10078        2018-08-05  20.8589    28.8190  32.9249
23          10094        2018-08-21  19.2817    23.4105  25.1669
            10095        2018-08-22  18.6661    24.2805  28.9239
            10096        2018-08-23  13.0033    22.2140  26.0739
            10097        2018-08-24  14.6072    23.8280  28.2319
            10098        2018-08-25  17.7442    23.2320  26.6609
            10099        2018-08-26  19.3282    25.3190  28.7739
            10100        2018-08-27  21.3633    28.0335  31.5979
            10100        2018-08-27  21.3633    28.0335  31.5979
24          10103        2018-08-30  20.4944    27.6785  32.0149
            10104        2018-08-31  19.0452    22.6697  24.1869
            10105        2018-09-01  17.9422    23.0238  25.8699
            10106        2018-09-02  18.7967    25.1263  27.9879

                         Apparent temp
index_count index_value
0           193              28.255025
            194              27.231644
            195              25.718047
            196              25.394786
            197              27.589549
            198              30.177302
            199              32.538369
1           911              27.107569
            912              24.604738
            913              20.824132
            914              26.984510
            915              32.207717
            916              28.746475
            917              30.316296
2           1277             26.633059
            1278             28.645500
            1279             29.184846
            1280             26.087340
            1281             26.447793
            1282             32.126100
            1283             32.890146
3           1648             26.939753
            1649             26.168406
            1650             19.546875
            1651             22.434126
            1652             25.877259
            1653             26.624630
            1654             28.974698
4           1660             26.564788
            1661             27.084616
...                                ...
20          9692             27.256289
            9693             28.071994
            9694             29.924211
            9695             31.424540
21          10036            26.933115
            10037            22.074012
            10038            21.520347
            10039            23.309739
            10040            27.850825
            10041            29.968547
            10042            31.853927
22          10072            24.790297
            10073            27.801965
            10074            31.547279
            10075            32.282189
            10076            30.880463
            10077            30.063428
            10078            32.649020
23          10094            26.304332
            10095            26.811693
            10096            22.013729
            10097            24.295597
            10098            25.255914
            10099            28.228850
            10100            32.194075
            10100            32.194075
24          10103            31.284742
            10104            25.429292
            10105            25.157072
            10106            27.727276

[170 rows x 5 columns]

In [22]:
weather_data_ctrl_immediate_days_7.DateTime.dtypes

dtype('O')

# IMPORTING SQL DATA

In [23]:
import sqlalchemy
import psycopg2

In [24]:
from sqlalchemy import create_engine 
# Postgres username, password, and database name 
POSTGRES_ADDRESS = 'localhost' ## INSERT YOUR DB ADDRESS
POSTGRES_PORT = '5432' 
POSTGRES_USERNAME = 'owner' ## CHANGE THIS TO YOUR POSTGRES USERNAME
POSTGRES_PASSWORD = 'abcd1234' ## CHANGE THIS TO YOUR POSTGRES PASSWORD 
POSTGRES_DBNAME = 'ohdsi' ## CHANGE THIS TO YOUR DATABASE NAME 
# A long string that contains the necessary Postgres login information 
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(username=POSTGRES_USERNAME,password=POSTGRES_PASSWORD,ipaddress=POSTGRES_ADDRESS,port=POSTGRES_PORT, 
dbname=POSTGRES_DBNAME)) 
# Create the connection 
cnx = create_engine(postgres_str)

## synPUF.person

In [25]:
synpuf_person = pd.read_sql_query('''SELECT * FROM synpuf5.person;''', cnx)
#synpuf_person = synpuf_person.set_index('person_id')
synpuf_person

,person_id,gender_concept_id,year_of_birth,month_of_birth,day_of_birth,time_of_birth,race_concept_id,ethnicity_concept_id,location_id,provider_id,care_site_id,person_source_value,gender_source_value,gender_source_concept_id,race_source_value,race_source_concept_id,ethnicity_source_value,ethnicity_source_concept_id
0,1,8507,1923,5,1,None,8527,38003564,1,None,None,00013D2EFD8E45D1,1,None,1,None,1,None
1,2,8507,1943,1,1,None,8527,38003564,2,None,None,00016F745862898F,1,None,1,None,1,None
2,3,8532,1936,9,1,None,8527,38003564,3,None,None,0001FDD721E223DC,2,None,1,None,1,None
3,4,8507,1941,6,1,None,0,38003563,4,None,None,00021CA6FF03E670,1,None,5,None,5,None
4,5,8507,1936,8,1,None,8527,38003564,5,None,None,00024B3D2352D2D0,1,None,1,None,1,None
5,6,8507,1943,10,1,None,8516,38003564,6,None,None,0002DAE1C81CC70D,1,None,2,None,2,None
6,7,8507,1922,7,1,None,8527,38003564,7,None,None,0002F28CE057345B,1,None,1,None,1,None
7,8,8507,1935,9,1,None,8527,38003564,8,None,None,000308435E3E5B76,1,None,1,None,1,None
8,9,8532,1976,9,1,None,8527,38003564,9,None,None,000345A39D4157C9,2,None,1,None,1,None
9,10,8532,1938,10,1,None,8516,38003564,10,None,None,00036A21B65B0206,2,None,2,None,2,None
10,11,8532,1934,2,1,None,8527,38003564,11,None,None,000489E7EAAD463F,2,None,1,None,1,None
11,12,8507,1929,6,1,None,8527,38003564,12,None,None,00048EF1F4791C68,1,None,1,None,1,None
12,13,8532,1936,7,1,None,8527,38003564,13,None,None,0004F0ABD505251D,2,None,1,None,1,None
13,14,8507,1934,5,1,None,8527,38003564,14,None,None,00052705243EA128,1,None,1,None,1,None
14,15,8532,1936,3,1,None,8527,38003564,15,None,None,00070B63745BE497,2,None,1,None,1,None
15,16,8507,1934,1,1,None,8527,38003564,16,None,None,0007E57CC13CE880,1,None,1,None,1,None
16,17,8532,1919,9,1,None,8516,38003564,17,None,None,0007F12A492FD25D,2,None,2,None,2,None
17,18,8532,1919,10,1,None,8516,38003564,18,None,None,000A005BA0BED3EA,2,None,2,None,2,None
18,19,8532,1942,7,1,None,8527,38003564,19,None,None,000B4662348C35B4,2,None,1,None,1,None
19,20,8507,1938,4,1,None,8527,38003564,20,None,None,000B97BA2314E971,1,None,1,None,1,None
20,21,8507,1932,8,1,None,8516,38003564,21,None,None,000C7486B11E7030,1,None,2,None,2,None
21,22,8507,1942,8,1,None,0,38003563,22,None,None,000D6D88463D8A76,1,None,5,None,5,None
22,23,8507,1932,7,1,None,8527,38003564,23,None,None,000DDD364C46E2C6,1,None,1,None,1,None
23,24,8507,1931,3,1,None,8527,38003564,24,None,None,000E374862A3C527,1,None,1,None,1,None
24,25,8507,1965,4,1,None,8527,38003564,25,None,None,00108066CA1FACCE,1,None,1,None,1,None
25,26,8532,1939,12,1,None,8527,38003564,26,None,None,0010D6F80D245D62,2,None,1,None,1,None
26,27,8532,1940,4,1,None,8527,38003564,27,None,None,0011714C14B52EEB,2,None,1,None,1,None
27,28,8507,1937,10,1,None,8527,38003564,28,None,None,0011CB1FE23E91AF,1,None,1,None,1,None
28,29,8507,1938,4,1,None,8527,38003564,29,None,None,0012AFEEC379A69D,1,None,1,None,1,None
29,30,8532,1959,11,1,None,8527,38003564,30,None,None,00131C35661B2926,2,None,1,None,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116322,116323,8507,1959,8,1,None,8527,38003564,159,None,None,FFF1CD7E8B423F18,1,None,1,None,1,None
116323,116324,8532,1956,12,1,None,8516,38003564,783,None,None,FFF210318A24632D,2,None,2,None,2,None
116324,116325,8532,1942,7,1,None,8527,38003564,683,None,None,FFF24EEE33E6F8CD,2,None,1,None,1,None
116325,116326,8532,1947,3,1,None,0,38003564,769,None,None,FFF2813198D935D3,2,None,3,None,3,None
116326,116327,8532,1910,2,1,None,8527,38003564,325,None,None,FFF2D72BB013621E,2,None,1,None,1,None
116327,116328,8507,1920,5,1,None,8527,38003564,642,None,None,FFF3369200B2F6ED,1,None,1,None,1,None
116328,116329,8507,1943,3,1,None,8527,38003564,730,None,None,FFF38437EE43B295,1,None,1,None,1,None
116329,116330,8507,1943,11,1,None,8516,38003564,273,None,None,FFF46A3796CB82BB,1,None,2,None,2,None
116330,116331,8532,1928,11,1,None,8527,38003564,78,None,None,FFF4730CB7D9A40B,2,None,1,None,1,None
116331,116332,8532,1925,8,1,None,8527,38003564,122,None,None,FFF47C94D62E4329,2,None,1,None,1,None
116332,116333,8507,1919,5,1,None,8527,38003564,1822,None,None,FFF546863DE1D8B4,1,None,1,None,1,None
116333,116334,8532,1950,2,1,None,8527,38003564,1360,None,None,FFF5D27EF3CAFE06,2,None,1,None,1,None
116334,116335,8532,1953,10,1,None,8527,38003564,34,None,None,FFF5F9218AB04A41,2,None,1,None,1,None
116335,116336,8532,1922,5,1,None,8527,38003564,161,None,None,FFF732400E2A42FA,2,None,1,None,1,None
116336,116337,8532,1940,6,1,None,8527,38003564,213,None,None,FFF7BF917D9AFF10,2,None,1,None,1,None
116337,116338,8507,1922,9,1,None,8527,38003564,701,None,None,FFF82A5A7D106016,1,None,1,None,1,None
116338,116339,8532,1920,1,1,None,8527,38003564,103,None,None,FFF8B49458F9FFA7,2,None,1,None,1,None
116339,116340,8507,1936,8,1,None,8527,38003564,311,None,None,FFF931503E89CB7C,1,None,1,None,1,None
116340,116341,8532,1935,6,1,None,8527,38003564,30,None,None,FFF9564A4E674C72,2,None,1,None,1,None
116341,116342,8532,1930,1,1,None,8527,38003564,1124,None,None,FFF9DAA4BC772047,2,None,1,None,1,None
116342,116343,8507,1959,7,1,None,8527,38003564,1320,None,None,FFFA950301FCA748,1,None,1,None,1,None
116343,116344,8532,1941,4,1,None,8527,38003564,3081,None,None,FFFB1DA1D16DE998,2,None,1,None,1,None
116344,116345,8532,1920,12,1,None,8527,38003564,887,None,None,FFFB72BFAF19FE53,2,None,1,None,1,None
116345,116346,8532,1936,12,1,None,8527,38003564,115,None,None,FFFC880E13CA6278,2,None,1,None,1,None
116346,116347,8507,1939,7,1,None,8527,38003564,286,None,None,FFFD1F9EE7AF231B,1,None,1,None,1,None
116347,116348,8532,1943,7,1,None,8527,38003564,26,None,None,FFFD7C464C94D136,2,None,1,None,1,None
116348,116349,8532,1916,6,1,None,8527,38003564,281,None,None,FFFE3ED9582AD46E,2,None,1,None,1,None
116349,116350,8532,1939,4,1,None,8527,38003564,249,None,None,FFFE7AB5D7F1725D,2,None,1,None,1,None
116350,116351,8507,1911,7,1,None,8527,38003564,415,None,None,FFFF29A2E1362059,1,None,1,None,1,None
116351,116352,8532,1952,4,1,None,8527,38003564,276,None,None,FFFF7C107A4E385A,2,None,1,None,1,None

## synPUF.visit_occurence

In [26]:
synpuf_visit_occurence = pd.read_sql_query('''SELECT * FROM synpuf5.visit_occurrence;''', cnx)
#synpuf_visit_occurence.set_index(['person_id','visit_start_date'])
#synpuf_visit_occurence[synpuf_visit_occurence[visit_start_date] == '2008-09-12']
synpuf_visit_occurence

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id
0,6,1,0,2009-07-25,None,2009-07-25,None,44818517,6.0,6.0,887733386680966,5.0
1,2,1,9202,2008-09-04,None,2008-09-04,None,44818517,2.0,2.0,542192281063886,1.0
2,5,1,0,2010-11-05,None,2010-11-05,None,44818517,5.0,5.0,887463387476539,4.0
3,4,1,0,2010-04-01,None,2010-04-01,None,44818517,4.0,4.0,887243388666441,3.0
4,3,1,0,2009-10-14,None,2009-10-14,None,44818517,3.0,3.0,887213386947664,2.0
5,1,1,9201,2010-03-12,None,2010-03-13,None,44818517,1.0,1.0,196661176988405,NaN
6,7,1,0,2010-08-17,None,2010-08-17,None,44818517,7.0,7.0,887893388307089,6.0
7,11,2,9201,2009-08-31,None,2009-09-02,None,44818517,13.0,10.0,196661177015632,10.0
8,26,2,0,2009-03-30,None,2009-03-30,None,44818517,28.0,23.0,887433386151111,25.0
9,22,2,0,2010-03-21,None,2010-03-21,None,44818517,24.0,21.0,887353386843897,21.0
10,10,2,9201,2010-06-26,None,2010-07-01,None,44818517,12.0,9.0,196261176983265,9.0
11,9,2,9201,2009-04-12,None,2009-04-18,None,44818517,10.0,9.0,196201177000368,8.0
12,8,2,9201,2009-09-17,None,2009-09-20,None,44818517,9.0,8.0,196091176981058,NaN
13,28,2,0,2009-07-03,None,2009-07-03,None,44818517,30.0,25.0,887443385121084,27.0
14,24,2,0,2010-02-19,None,2010-02-19,None,44818517,26.0,20.0,887393386608161,23.0
15,29,2,0,2009-07-16,None,2009-07-16,None,44818517,20.0,17.0,887453384924494,28.0
16,21,2,0,2009-01-17,None,2009-01-17,None,44818517,23.0,20.0,887293389131196,20.0
17,13,2,9202,2009-06-23,None,2009-06-23,None,44818517,15.0,12.0,542282281644416,12.0
18,30,2,0,2010-06-18,None,2010-06-27,None,44818517,31.0,26.0,887513388218955,29.0
19,19,2,0,2009-08-11,None,2009-08-11,None,44818517,21.0,18.0,887243387711309,18.0
20,18,2,0,2009-10-01,None,2009-10-01,None,44818517,20.0,17.0,887243387365395,17.0
21,17,2,0,2010-05-04,None,2010-05-04,None,44818517,19.0,16.0,887233384922699,16.0
22,16,2,0,2010-08-03,None,2010-08-03,None,44818517,18.0,15.0,887223385558356,15.0
23,15,2,0,2009-08-24,None,2009-08-24,None,44818517,17.0,14.0,887023387989281,14.0
24,14,2,0,2010-05-29,None,2010-05-29,None,44818517,16.0,13.0,887023385728164,13.0
25,31,2,0,2009-03-08,None,2009-03-08,None,44818517,32.0,27.0,887523385536820,30.0
26,32,2,0,2008-10-04,None,2008-10-04,None,44818517,33.0,28.0,887523386668713,31.0
27,33,2,0,2010-02-24,None,2010-02-26,None,44818517,34.0,29.0,887603386008014,32.0
28,23,2,0,2009-01-05,None,2009-01-05,None,44818517,25.0,15.0,887383388842050,22.0
29,34,2,0,2009-06-21,None,2009-06-21,None,44818517,35.0,30.0,887603386081276,33.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5579512,5579545,116352,0,2010-03-12,None,2010-03-12,None,44818517,1883.0,1224.0,887753385569456,5579544.0
5579513,5579546,116352,0,2009-02-05,None,2009-02-05,None,44818517,251860.0,9668.0,887753386060584,5579545.0
5579514,5579547,116352,0,2008-03-04,None,2008-03-04,None,44818517,195087.0,16069.0,887773387399704,5579546.0
5579515,5579548,116352,0,2010-01-04,None,2010-01-04,None,44818517,174536.0,80879.0,887773387926881,5579547.0
5579516,5579549,116352,0,2008-01-26,None,2008-01-26,None,44818517,275.0,178.0,887773389377273,5579548.0
5579517,5579550,116352,0,2010-03-12,None,2010-03-12,None,44818517,169773.0,9662.0,887783386454443,5579549.0
5579518,5579551,116352,0,2009-09-04,None,2009-09-04,None,44818517,627738.0,126559.0,887783387794472,5579550.0
5579519,5579552,116352,0,2010-02-10,None,2010-02-19,None,44818517,98155.0,21977.0,887793387933148,5579551.0
5579520,5579553,116352,0,2009-12-21,None,2009-12-21,None,44818517,255641.0,9662.0,887803386457377,5579552.0
5579521,5579554,116352,0,2008-04-19,None,2008-04-19,None,44818517,645.0,40.0,887803389003089,5579553.0
5579522,5579555,116352,0,2009-06-26,None,2009-06-26,None,44818517,45072.0,25791.0,887813387222350,5579554.0
5579523,5579556,116352,0,2009-01-28,None,2009-01-28,None,44818517,51441.0,28952.0,887833387877235,5579555.0
5579524,5579557,116352,0,2010-03-03,None,2010-03-03,None,44818517,89273.0,49894.0,887833389173429,5579556.0
5579525,5579558,116352,0,2009-05-16,None,2009-05-16,None,44818517,46261.0,9662.0,887843388360188,5579557.0
5579526,5579559,116352,0,2009-10-20,None,2009-10-20,None,44818517,154391.0,72980.0,887863388109812,5579558.0
5579527,5579560,116352,0,2008-03-11,None,2008-03-11,None,44818517,374239.0,5534.0,887873385296591,5579559.0
5579528,5579561,116352,0,2009-11-26,None,2009-11-26,None,44818517,98509.0,16069.0,887873388874193,5579560.0
5579529,5579562,116352,0,2008-06-23,None,2008-06-23,None,44818517,251857.0,47111.0,887883385490722,5579561.0
5579530,5579563,116352,0,2008-09-24,None,2008-09-24,None,44818517,26545.0,22082.0,887883388610042,5579562.0
5579531,5579564,116352,0,2008-09-06,None,2008-09-06,None,44818517,587952.0,224269.0,887883389504190,5579563.0
5579532,5579565,116352,0,2008-11-25,None,2008-11-25,None,44818517,186301.0,21989.0,887893388582164,5579564.0
5579533,5579566,116352,0,2009-01-17,None,2009-01-19,None,44818517,580897.0,221992.0,887903388519091,5579565.0
5579534,5579567,116352,0,2010-01-26,None,2010-01-26,None,44818517,230551.0,26371.0,887903389407975,5579566.0
5579535,5579568,116352,0,2009-09-23,None,2009-09-23,None,44818517,186306.0,9661.0,887913385951449,5579567.0
5579536,5579569,116352,0,2009-05-18,None,2009-05-18,None,44818517,1883.0,1224.0,887943385843008,5579568.0
5579537,5579570,116352,0,2010-02-16,None,2010-02-16,None,44818517,132787.0,64478.0,887953385122872,5579569.0
5579538,5579571,116352,0,2008-10-04,None,2008-10-04,None,44818517,112352.0,56126.0,887963389308382,5579570.0
5579539,5579572,116352,0,2009-06-08,None,2009-06-08,None,44818517,79815.0,41969.0,887973388204189,5579571.0
5579540,5579573,116352,0,2008-09-13,None,2008-09-13,None,44818517,149168.0,5534.0,887983388258849,5579572.0
5579541,5579574,116352,0,2009-06-25,None,2009-06-25,None,44818517,606359.0,46112.0,887993386918670,5579573.0

In [27]:
# Below is the list of the dates from the Final heat wave case days
list_of_dates_case = refined_list['DateTime'].tolist()
list_of_dates_case

['1991-07-20',
 '1991-07-21',
 '1991-07-23',
 '1993-07-07',
 '1993-07-08',
 '1993-07-09',
 '1993-07-10',
 '1994-07-08',
 '1994-07-09',
 '1995-07-14',
 '1995-07-15',
 '1995-07-26',
 '1995-07-27',
 '1995-07-28',
 '1995-07-29',
 '1997-07-15',
 '1997-07-16',
 '1997-07-17',
 '1999-07-04',
 '1999-07-05',
 '1999-07-06',
 '2001-08-07',
 '2001-08-08',
 '2001-08-09',
 '2001-08-10',
 '2002-07-03',
 '2002-07-04',
 '2005-08-13',
 '2005-08-14',
 '2006-08-01',
 '2006-08-02',
 '2006-08-03',
 '2010-07-05',
 '2010-07-06',
 '2010-07-07',
 '2010-07-16',
 '2010-07-17',
 '2011-07-21',
 '2011-07-22',
 '2011-07-23',
 '2011-07-24',
 '2013-07-06',
 '2013-07-07',
 '2013-07-14',
 '2013-07-15',
 '2013-07-18',
 '2013-07-19',
 '2013-07-20',
 '2015-07-19',
 '2015-07-20',
 '2015-07-28',
 '2015-07-29',
 '2016-08-10',
 '2016-08-11',
 '2016-08-12',
 '2016-08-13',
 '2016-08-14',
 '2016-08-15',
 '2017-07-19',
 '2017-07-20',
 '2017-07-21',
 '2018-07-01',
 '2018-07-02',
 '2018-07-03',
 '2018-08-06',
 '2018-08-07',
 '2018-08-08',
 '2018-08-28',
 '2018-08-29',
 '2018-09-03',
 '2018-09-05']

## synpuf_visit_occurence_filtered CASE

In [28]:
list_of_dates_case
synpuf_visit_occurence_filtered = pd.read_sql_query('''SELECT * FROM synpuf5.visit_occurrence WHERE visit_start_date in %s''' % str(tuple(list_of_dates_case)), cnx)

synpuf_visit_occurence_filtered

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id
0,471,13,0,2010-07-17,None,2010-07-17,None,44818517,380.0,256.0,887593386618796,470.0
1,740,17,9202,2010-07-07,None,2010-07-07,None,44818517,606.0,411.0,542322281522475,739.0
2,779,17,0,2010-07-16,None,2010-07-16,None,44818517,632.0,431.0,887103386766382,778.0
3,1219,23,0,2010-07-07,None,2010-07-07,None,44818517,1010.0,634.0,887293386789445,1218.0
4,1252,23,0,2010-07-17,None,2010-07-17,None,44818517,1038.0,655.0,887813387769226,1251.0
5,1525,30,0,2010-07-16,None,2010-07-16,None,44818517,1273.0,802.0,887163384929760,1524.0
6,1852,35,0,2010-07-05,None,2010-07-05,None,44818517,1571.0,1030.0,887583385153491,1851.0
7,2323,46,0,2010-07-17,None,2010-07-17,None,44818517,1963.0,1284.0,887073388666061,2322.0
8,2318,46,9202,2010-07-07,None,2010-07-07,None,44818517,1960.0,1281.0,542822280971315,2317.0
9,2596,55,0,2010-07-17,None,2010-07-17,None,44818517,2204.0,1440.0,887613388395060,2595.0
10,3118,66,0,2010-07-16,None,2010-07-16,None,44818517,2660.0,1795.0,887293388835643,3117.0
11,3120,66,0,2010-07-16,None,2010-07-16,None,44818517,2662.0,1797.0,887313385303374,3119.0
12,3314,68,0,2010-07-06,None,2010-07-06,None,44818517,2769.0,1883.0,887813388047987,3313.0
13,3628,76,0,2010-07-06,None,2010-07-06,None,44818517,3081.0,2134.0,887203387444654,3627.0
14,3631,76,0,2010-07-16,None,2010-07-16,None,44818517,3083.0,2136.0,887243385302120,3630.0
15,3841,80,0,2010-07-06,None,2010-07-06,None,44818517,2108.0,1334.0,887503385067611,3840.0
16,4358,86,0,2010-07-05,None,2010-07-05,None,44818517,3679.0,2587.0,887943388493520,4357.0
17,4604,90,0,2010-07-07,None,2010-07-07,None,44818517,3848.0,2684.0,887013388796931,4603.0
18,4916,95,0,2010-07-16,None,2010-07-16,None,44818517,4125.0,2875.0,887233386486523,4915.0
19,5782,107,9202,2010-07-17,None,2010-07-17,None,44818517,4810.0,3335.0,542202281314803,5781.0
20,5888,108,0,2010-07-05,None,2010-07-05,None,44818517,703.0,423.0,887563389335091,5887.0
21,5915,108,0,2010-07-16,None,2010-07-16,None,44818517,4911.0,3389.0,887843388893046,5914.0
22,5994,109,0,2010-07-06,None,2010-07-06,None,44818517,4981.0,3420.0,887903386680874,5993.0
23,6263,117,0,2010-07-05,None,2010-07-05,None,44818517,5197.0,3580.0,887683387365046,6262.0
24,6487,123,0,2010-07-05,None,2010-07-05,None,44818517,5380.0,3699.0,887753384853202,6486.0
25,6499,123,0,2010-07-16,None,2010-07-16,None,44818517,5388.0,3652.0,887803387822101,6498.0
26,6509,123,0,2010-07-16,None,2010-07-16,None,44818517,152.0,94.0,887853387562654,6508.0
27,6637,127,0,2010-07-06,None,2010-07-06,None,44818517,5491.0,393.0,887023386214341,6636.0
28,6749,132,0,2010-07-17,None,2010-07-17,None,44818517,5577.0,3815.0,887043386727457,6748.0
29,6943,136,0,2010-07-05,None,2010-07-05,None,44818517,5740.0,3926.0,887653389373564,6942.0
...,...,...,...,...,...,...,...,...,...,...,...,...
18513,5572264,116200,0,2010-07-17,None,2010-07-17,None,44818517,635246.0,71565.0,887803385384612,5572263.0
18514,5572414,116203,0,2010-07-17,None,2010-07-17,None,44818517,372235.0,152695.0,887213387545810,5572413.0
18515,5573408,116226,0,2010-07-05,None,2010-07-05,None,44818517,77030.0,15266.0,887053388243225,5573407.0
18516,5572552,116205,0,2010-07-17,None,2010-07-17,None,44818517,75215.0,34618.0,887613386498105,5572551.0
18517,5572922,116214,0,2010-07-16,None,2010-07-16,None,44818517,107631.0,5453.0,887463388842298,5572921.0
18518,5573281,116222,0,2010-07-17,None,2010-07-17,None,44818517,61603.0,1240.0,887433387675539,5573280.0
18519,5573849,116233,9202,2010-07-05,None,2010-07-05,None,44818517,49559.0,4705.0,542212281060039,5573848.0
18520,5573538,116228,0,2010-07-17,None,2010-07-17,None,44818517,545138.0,36944.0,887713387559063,5573537.0
18521,5573545,116229,0,2010-07-06,None,2010-07-06,None,44818517,223647.0,15528.0,887043385493518,5573544.0
18522,5574706,116248,9202,2010-07-16,None,2010-08-05,None,44818517,207007.0,51.0,542552281489581,5574705.0
18523,5574479,116241,0,2010-07-17,None,2010-07-17,None,44818517,172190.0,79934.0,887533388159733,5574478.0
18524,5576193,116276,9201,2010-07-06,None,2010-07-07,None,44818517,19358.0,4572.0,196881176993090,NaN
18525,5574624,116246,0,2010-07-05,None,2010-07-05,None,44818517,341358.0,473.0,887143388411447,5574623.0
18526,5575278,116259,0,2010-07-16,None,2010-07-16,None,44818517,91923.0,47321.0,887323385365381,5575277.0
18527,5575657,116267,0,2010-07-16,None,2010-07-16,None,44818517,108898.0,54649.0,887363386959146,5575656.0
18528,5576242,116276,0,2010-07-17,None,2010-07-21,None,44818517,436760.0,92921.0,887673387231011,5576241.0
18529,5576495,116284,0,2010-07-05,None,2010-07-05,None,44818517,299449.0,69597.0,887843388552681,5576494.0
18530,5578360,116324,0,2010-07-06,None,2010-07-06,None,44818517,252873.0,81476.0,887703386246580,5578359.0
18531,5577544,116303,0,2010-07-16,None,2010-07-16,None,44818517,120684.0,6252.0,887693388890545,5577543.0
18532,5578247,116322,0,2010-07-07,None,2010-07-07,None,44818517,14415.0,393.0,887403386217933,5578246.0
18533,5576977,116292,0,2010-07-16,None,2010-07-16,None,44818517,459676.0,182974.0,887743387088027,5576976.0
18534,5577350,116298,9202,2010-07-05,None,2010-07-05,None,44818517,21266.0,13217.0,542582280963410,NaN
18535,5577362,116299,9202,2010-07-17,None,2010-07-17,None,44818517,37732.0,3176.0,542462281164345,5577361.0
18536,5579065,116340,0,2010-07-05,None,2010-07-05,None,44818517,437218.0,1352.0,887773388814492,5579064.0
18537,5578302,116324,0,2010-07-17,None,2010-07-17,None,44818517,68470.0,36866.0,887043389011581,5578301.0
18538,5578309,116324,0,2010-07-06,None,2010-07-06,None,44818517,1909.0,1243.0,887153387029060,5578308.0
18539,5578348,116324,0,2010-07-07,None,2010-07-07,None,44818517,902.0,393.0,887603388685349,5578347.0
18540,5579040,116340,0,2010-07-07,None,2010-07-07,None,44818517,227395.0,11277.0,887493387697081,5579039.0
18541,5579042,116340,0,2010-07-17,None,2010-07-17,None,44818517,156265.0,73664.0,887503385203589,5579041.0
18542,5579207,116343,9202,2010-07-07,None,2010-07-07,None,44818517,328962.0,3397.0,542202281637545,5579206.0

## Patient age taken from the year patient born to the year of 'visit_start_date'

In [29]:
synpuf_visit_occurence_filtered_withAge = synpuf_visit_occurence_filtered.merge(synpuf_person[list(('person_id','year_of_birth'))])

synpuf_visit_occurence_filtered_withAge.visit_start_date = pd.to_datetime(synpuf_visit_occurence_filtered_withAge['visit_start_date'])
synpuf_visit_occurence_filtered_withAge['admit_year'] =  pd.DatetimeIndex(synpuf_visit_occurence_filtered_withAge['visit_start_date']).year
synpuf_visit_occurence_filtered_withAge['patient_age'] = synpuf_visit_occurence_filtered_withAge['admit_year'] - synpuf_visit_occurence_filtered_withAge['year_of_birth']

synpuf_visit_occurence_filtered_withAge

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age
0,471,13,0,2010-07-17,None,2010-07-17,None,44818517,380.0,256.0,887593386618796,470.0,1936,2010,74
1,740,17,9202,2010-07-07,None,2010-07-07,None,44818517,606.0,411.0,542322281522475,739.0,1919,2010,91
2,779,17,0,2010-07-16,None,2010-07-16,None,44818517,632.0,431.0,887103386766382,778.0,1919,2010,91
3,1219,23,0,2010-07-07,None,2010-07-07,None,44818517,1010.0,634.0,887293386789445,1218.0,1932,2010,78
4,1252,23,0,2010-07-17,None,2010-07-17,None,44818517,1038.0,655.0,887813387769226,1251.0,1932,2010,78
5,1525,30,0,2010-07-16,None,2010-07-16,None,44818517,1273.0,802.0,887163384929760,1524.0,1959,2010,51
6,1852,35,0,2010-07-05,None,2010-07-05,None,44818517,1571.0,1030.0,887583385153491,1851.0,1911,2010,99
7,2323,46,0,2010-07-17,None,2010-07-17,None,44818517,1963.0,1284.0,887073388666061,2322.0,1931,2010,79
8,2318,46,9202,2010-07-07,None,2010-07-07,None,44818517,1960.0,1281.0,542822280971315,2317.0,1931,2010,79
9,2596,55,0,2010-07-17,None,2010-07-17,None,44818517,2204.0,1440.0,887613388395060,2595.0,1924,2010,86
10,3118,66,0,2010-07-16,None,2010-07-16,None,44818517,2660.0,1795.0,887293388835643,3117.0,1920,2010,90
11,3120,66,0,2010-07-16,None,2010-07-16,None,44818517,2662.0,1797.0,887313385303374,3119.0,1920,2010,90
12,3314,68,0,2010-07-06,None,2010-07-06,None,44818517,2769.0,1883.0,887813388047987,3313.0,1954,2010,56
13,3628,76,0,2010-07-06,None,2010-07-06,None,44818517,3081.0,2134.0,887203387444654,3627.0,1938,2010,72
14,3631,76,0,2010-07-16,None,2010-07-16,None,44818517,3083.0,2136.0,887243385302120,3630.0,1938,2010,72
15,3841,80,0,2010-07-06,None,2010-07-06,None,44818517,2108.0,1334.0,887503385067611,3840.0,1933,2010,77
16,4358,86,0,2010-07-05,None,2010-07-05,None,44818517,3679.0,2587.0,887943388493520,4357.0,1926,2010,84
17,4604,90,0,2010-07-07,None,2010-07-07,None,44818517,3848.0,2684.0,887013388796931,4603.0,1925,2010,85
18,4916,95,0,2010-07-16,None,2010-07-16,None,44818517,4125.0,2875.0,887233386486523,4915.0,1931,2010,79
19,5782,107,9202,2010-07-17,None,2010-07-17,None,44818517,4810.0,3335.0,542202281314803,5781.0,1960,2010,50
20,5888,108,0,2010-07-05,None,2010-07-05,None,44818517,703.0,423.0,887563389335091,5887.0,1927,2010,83
21,5915,108,0,2010-07-16,None,2010-07-16,None,44818517,4911.0,3389.0,887843388893046,5914.0,1927,2010,83
22,5994,109,0,2010-07-06,None,2010-07-06,None,44818517,4981.0,3420.0,887903386680874,5993.0,1955,2010,55
23,6263,117,0,2010-07-05,None,2010-07-05,None,44818517,5197.0,3580.0,887683387365046,6262.0,1937,2010,73
24,6487,123,0,2010-07-05,None,2010-07-05,None,44818517,5380.0,3699.0,887753384853202,6486.0,1967,2010,43
25,6499,123,0,2010-07-16,None,2010-07-16,None,44818517,5388.0,3652.0,887803387822101,6498.0,1967,2010,43
26,6509,123,0,2010-07-16,None,2010-07-16,None,44818517,152.0,94.0,887853387562654,6508.0,1967,2010,43
27,6637,127,0,2010-07-06,None,2010-07-06,None,44818517,5491.0,393.0,887023386214341,6636.0,1942,2010,68
28,6749,132,0,2010-07-17,None,2010-07-17,None,44818517,5577.0,3815.0,887043386727457,6748.0,1937,2010,73
29,6943,136,0,2010-07-05,None,2010-07-05,None,44818517,5740.0,3926.0,887653389373564,6942.0,1943,2010,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18513,5572414,116203,0,2010-07-17,None,2010-07-17,None,44818517,372235.0,152695.0,887213387545810,5572413.0,1919,2010,91
18514,5572264,116200,0,2010-07-17,None,2010-07-17,None,44818517,635246.0,71565.0,887803385384612,5572263.0,1925,2010,85
18515,5573408,116226,0,2010-07-05,None,2010-07-05,None,44818517,77030.0,15266.0,887053388243225,5573407.0,1941,2010,69
18516,5572552,116205,0,2010-07-17,None,2010-07-17,None,44818517,75215.0,34618.0,887613386498105,5572551.0,1914,2010,96
18517,5572922,116214,0,2010-07-16,None,2010-07-16,None,44818517,107631.0,5453.0,887463388842298,5572921.0,1938,2010,72
18518,5573281,116222,0,2010-07-17,None,2010-07-17,None,44818517,61603.0,1240.0,887433387675539,5573280.0,1912,2010,98
18519,5573849,116233,9202,2010-07-05,None,2010-07-05,None,44818517,49559.0,4705.0,542212281060039,5573848.0,1922,2010,88
18520,5573538,116228,0,2010-07-17,None,2010-07-17,None,44818517,545138.0,36944.0,887713387559063,5573537.0,1939,2010,71
18521,5573545,116229,0,2010-07-06,None,2010-07-06,None,44818517,223647.0,15528.0,887043385493518,5573544.0,1936,2010,74
18522,5574706,116248,9202,2010-07-16,None,2010-08-05,None,44818517,207007.0,51.0,542552281489581,5574705.0,1914,2010,96
18523,5574479,116241,0,2010-07-17,None,2010-07-17,None,44818517,172190.0,79934.0,887533388159733,5574478.0,1929,2010,81
18524,5576193,116276,9201,2010-07-06,None,2010-07-07,None,44818517,19358.0,4572.0,196881176993090,NaN,1925,2010,85
18525,5576242,116276,0,2010-07-17,None,2010-07-21,None,44818517,436760.0,92921.0,887673387231011,5576241.0,1925,2010,85
18526,5574624,116246,0,2010-07-05,None,2010-07-05,None,44818517,341358.0,473.0,887143388411447,5574623.0,1939,2010,71
18527,5575278,116259,0,2010-07-16,None,2010-07-16,None,44818517,91923.0,47321.0,887323385365381,5575277.0,1927,2010,83
18528,5575657,116267,0,2010-07-16,None,2010-07-16,None,44818517,108898.0,54649.0,887363386959146,5575656.0,1956,2010,54
18529,5576495,116284,0,2010-07-05,None,2010-07-05,None,44818517,299449.0,69597.0,887843388552681,5576494.0,1936,2010,74
18530,5578360,116324,0,2010-07-06,None,2010-07-06,None,44818517,252873.0,81476.0,887703386246580,5578359.0,1956,2010,54
18531,5578302,116324,0,2010-07-17,None,2010-07-17,None,44818517,68470.0,36866.0,887043389011581,5578301.0,1956,2010,54
18532,5578309,116324,0,2010-07-06,None,2010-07-06,None,44818517,1909.0,1243.0,887153387029060,5578308.0,1956,2010,54
18533,5578348,116324,0,2010-07-07,None,2010-07-07,None,44818517,902.0,393.0,887603388685349,5578347.0,1956,2010,54
18534,5577544,116303,0,2010-07-16,None,2010-07-16,None,44818517,120684.0,6252.0,887693388890545,5577543.0,1940,2010,70
18535,5578247,116322,0,2010-07-07,None,2010-07-07,None,44818517,14415.0,393.0,887403386217933,5578246.0,1951,2010,59
18536,5576977,116292,0,2010-07-16,None,2010-07-16,None,44818517,459676.0,182974.0,887743387088027,5576976.0,1930,2010,80
18537,5577350,116298,9202,2010-07-05,None,2010-07-05,None,44818517,21266.0,13217.0,542582280963410,NaN,1934,2010,76
18538,5577362,116299,9202,2010-07-17,None,2010-07-17,None,44818517,37732.0,3176.0,542462281164345,5577361.0,1932,2010,78
18539,5579065,116340,0,2010-07-05,None,2010-07-05,None,44818517,437218.0,1352.0,887773388814492,5579064.0,1936,2010,74
18540,5579040,116340,0,2010-07-07,None,2010-07-07,None,44818517,227395.0,11277.0,887493387697081,5579039.0,1936,2010,74
18541,5579042,116340,0,2010-07-17,None,2010-07-17,None,44818517,156265.0,73664.0,887503385203589,5579041.0,1936,2010,74
18542,5579207,116343,9202,2010-07-07,None,2010-07-07,None,44818517,328962.0,3397.0,542202281637545,5579206.0,1959,2010,51

## Creating Age slot (10 years each)

In [30]:
synpuf_visit_occurence_filtered_withAge = synpuf_visit_occurence_filtered_withAge.assign(
    Age_Slot = pd.cut(
        synpuf_visit_occurence_filtered_withAge.patient_age,
        [0,10,20,30,40,50,60,70,80,90,100],
        labels=['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100']))

synpuf_visit_occurence_filtered_withAge

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age,Age_Slot
0,471,13,0,2010-07-17,None,2010-07-17,None,44818517,380.0,256.0,887593386618796,470.0,1936,2010,74,70-80
1,740,17,9202,2010-07-07,None,2010-07-07,None,44818517,606.0,411.0,542322281522475,739.0,1919,2010,91,90-100
2,779,17,0,2010-07-16,None,2010-07-16,None,44818517,632.0,431.0,887103386766382,778.0,1919,2010,91,90-100
3,1219,23,0,2010-07-07,None,2010-07-07,None,44818517,1010.0,634.0,887293386789445,1218.0,1932,2010,78,70-80
4,1252,23,0,2010-07-17,None,2010-07-17,None,44818517,1038.0,655.0,887813387769226,1251.0,1932,2010,78,70-80
5,1525,30,0,2010-07-16,None,2010-07-16,None,44818517,1273.0,802.0,887163384929760,1524.0,1959,2010,51,50-60
6,1852,35,0,2010-07-05,None,2010-07-05,None,44818517,1571.0,1030.0,887583385153491,1851.0,1911,2010,99,90-100
7,2323,46,0,2010-07-17,None,2010-07-17,None,44818517,1963.0,1284.0,887073388666061,2322.0,1931,2010,79,70-80
8,2318,46,9202,2010-07-07,None,2010-07-07,None,44818517,1960.0,1281.0,542822280971315,2317.0,1931,2010,79,70-80
9,2596,55,0,2010-07-17,None,2010-07-17,None,44818517,2204.0,1440.0,887613388395060,2595.0,1924,2010,86,80-90
10,3118,66,0,2010-07-16,None,2010-07-16,None,44818517,2660.0,1795.0,887293388835643,3117.0,1920,2010,90,80-90
11,3120,66,0,2010-07-16,None,2010-07-16,None,44818517,2662.0,1797.0,887313385303374,3119.0,1920,2010,90,80-90
12,3314,68,0,2010-07-06,None,2010-07-06,None,44818517,2769.0,1883.0,887813388047987,3313.0,1954,2010,56,50-60
13,3628,76,0,2010-07-06,None,2010-07-06,None,44818517,3081.0,2134.0,887203387444654,3627.0,1938,2010,72,70-80
14,3631,76,0,2010-07-16,None,2010-07-16,None,44818517,3083.0,2136.0,887243385302120,3630.0,1938,2010,72,70-80
15,3841,80,0,2010-07-06,None,2010-07-06,None,44818517,2108.0,1334.0,887503385067611,3840.0,1933,2010,77,70-80
16,4358,86,0,2010-07-05,None,2010-07-05,None,44818517,3679.0,2587.0,887943388493520,4357.0,1926,2010,84,80-90
17,4604,90,0,2010-07-07,None,2010-07-07,None,44818517,3848.0,2684.0,887013388796931,4603.0,1925,2010,85,80-90
18,4916,95,0,2010-07-16,None,2010-07-16,None,44818517,4125.0,2875.0,887233386486523,4915.0,1931,2010,79,70-80
19,5782,107,9202,2010-07-17,None,2010-07-17,None,44818517,4810.0,3335.0,542202281314803,5781.0,1960,2010,50,40-50
20,5888,108,0,2010-07-05,None,2010-07-05,None,44818517,703.0,423.0,887563389335091,5887.0,1927,2010,83,80-90
21,5915,108,0,2010-07-16,None,2010-07-16,None,44818517,4911.0,3389.0,887843388893046,5914.0,1927,2010,83,80-90
22,5994,109,0,2010-07-06,None,2010-07-06,None,44818517,4981.0,3420.0,887903386680874,5993.0,1955,2010,55,50-60
23,6263,117,0,2010-07-05,None,2010-07-05,None,44818517,5197.0,3580.0,887683387365046,6262.0,1937,2010,73,70-80
24,6487,123,0,2010-07-05,None,2010-07-05,None,44818517,5380.0,3699.0,887753384853202,6486.0,1967,2010,43,40-50
25,6499,123,0,2010-07-16,None,2010-07-16,None,44818517,5388.0,3652.0,887803387822101,6498.0,1967,2010,43,40-50
26,6509,123,0,2010-07-16,None,2010-07-16,None,44818517,152.0,94.0,887853387562654,6508.0,1967,2010,43,40-50
27,6637,127,0,2010-07-06,None,2010-07-06,None,44818517,5491.0,393.0,887023386214341,6636.0,1942,2010,68,60-70
28,6749,132,0,2010-07-17,None,2010-07-17,None,44818517,5577.0,3815.0,887043386727457,6748.0,1937,2010,73,70-80
29,6943,136,0,2010-07-05,None,2010-07-05,None,44818517,5740.0,3926.0,887653389373564,6942.0,1943,2010,67,60-70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18513,5572414,116203,0,2010-07-17,None,2010-07-17,None,44818517,372235.0,152695.0,887213387545810,5572413.0,1919,2010,91,90-100
18514,5572264,116200,0,2010-07-17,None,2010-07-17,None,44818517,635246.0,71565.0,887803385384612,5572263.0,1925,2010,85,80-90
18515,5573408,116226,0,2010-07-05,None,2010-07-05,None,44818517,77030.0,15266.0,887053388243225,5573407.0,1941,2010,69,60-70
18516,5572552,116205,0,2010-07-17,None,2010-07-17,None,44818517,75215.0,34618.0,887613386498105,5572551.0,1914,2010,96,90-100
18517,5572922,116214,0,2010-07-16,None,2010-07-16,None,44818517,107631.0,5453.0,887463388842298,5572921.0,1938,2010,72,70-80
18518,5573281,116222,0,2010-07-17,None,2010-07-17,None,44818517,61603.0,1240.0,887433387675539,5573280.0,1912,2010,98,90-100
18519,5573849,116233,9202,2010-07-05,None,2010-07-05,None,44818517,49559.0,4705.0,542212281060039,5573848.0,1922,2010,88,80-90
18520,5573538,116228,0,2010-07-17,None,2010-07-17,None,44818517,545138.0,36944.0,887713387559063,5573537.0,1939,2010,71,70-80
18521,5573545,116229,0,2010-07-06,None,2010-07-06,None,44818517,223647.0,15528.0,887043385493518,5573544.0,1936,2010,74,70-80
18522,5574706,116248,9202,2010-07-16,None,2010-08-05,None,44818517,207007.0,51.0,542552281489581,5574705.0,1914,2010,96,90-100
18523,5574479,116241,0,2010-07-17,None,2010-07-17,None,44818517,172190.0,79934.0,887533388159733,5574478.0,1929,2010,81,80-90
18524,5576193,116276,9201,2010-07-06,None,2010-07-07,None,44818517,19358.0,4572.0,196881176993090,NaN,1925,2010,85,80-90
18525,5576242,116276,0,2010-07-17,None,2010-07-21,None,44818517,436760.0,92921.0,887673387231011,5576241.0,1925,2010,85,80-90
18526,5574624,116246,0,2010-07-05,None,2010-07-05,None,44818517,341358.0,473.0,887143388411447,5574623.0,1939,2010,71,70-80
18527,5575278,116259,0,2010-07-16,None,2010-07-16,None,44818517,91923.0,47321.0,887323385365381,5575277.0,1927,2010,83,80-90
18528,5575657,116267,0,2010-07-16,None,2010-07-16,None,44818517,108898.0,54649.0,887363386959146,5575656.0,1956,2010,54,50-60
18529,5576495,116284,0,2010-07-05,None,2010-07-05,None,44818517,299449.0,69597.0,887843388552681,5576494.0,1936,2010,74,70-80
18530,5578360,116324,0,2010-07-06,None,2010-07-06,None,44818517,252873.0,81476.0,887703386246580,5578359.0,1956,2010,54,50-60
18531,5578302,116324,0,2010-07-17,None,2010-07-17,None,44818517,68470.0,36866.0,887043389011581,5578301.0,1956,2010,54,50-60
18532,5578309,116324,0,2010-07-06,None,2010-07-06,None,44818517,1909.0,1243.0,887153387029060,5578308.0,1956,2010,54,50-60
18533,5578348,116324,0,2010-07-07,None,2010-07-07,None,44818517,902.0,393.0,887603388685349,5578347.0,1956,2010,54,50-60
18534,5577544,116303,0,2010-07-16,None,2010-07-16,None,44818517,120684.0,6252.0,887693388890545,5577543.0,1940,2010,70,60-70
18535,5578247,116322,0,2010-07-07,None,2010-07-07,None,44818517,14415.0,393.0,887403386217933,5578246.0,1951,2010,59,50-60
18536,5576977,116292,0,2010-07-16,None,2010-07-16,None,44818517,459676.0,182974.0,887743387088027,5576976.0,1930,2010,80,70-80
18537,5577350,116298,9202,2010-07-05,None,2010-07-05,None,44818517,21266.0,13217.0,542582280963410,NaN,1934,2010,76,70-80
18538,5577362,116299,9202,2010-07-17,None,2010-07-17,None,44818517,37732.0,3176.0,542462281164345,5577361.0,1932,2010,78,70-80
18539,5579065,116340,0,2010-07-05,None,2010-07-05,None,44818517,437218.0,1352.0,887773388814492,5579064.0,1936,2010,74,70-80
18540,5579040,116340,0,2010-07-07,None,2010-07-07,None,44818517,227395.0,11277.0,887493387697081,5579039.0,1936,2010,74,70-80
18541,5579042,116340,0,2010-07-17,None,2010-07-17,None,44818517,156265.0,73664.0,887503385203589,5579041.0,1936,2010,74,70-80
18542,5579207,116343,9202,2010-07-07,None,2010-07-07,None,44818517,328962.0,3397.0,542202281637545,5579206.0,1959,2010,51,50-60

## synpuf_visit_occurence_filtered CONTROL_Immediate_days

In [31]:
# Below is the list of the dates from the Final heat wave case days
list_of_dates_control = weather_data_ctrl_immediate_days['DateTime'].tolist()
list_of_dates_control

['1991-07-17',
 '1991-07-18',
 '1991-07-19',
 '1993-07-03',
 '1993-07-04',
 '1993-07-05',
 '1993-07-06',
 '1994-07-06',
 '1994-07-07',
 '1995-07-12',
 '1995-07-13',
 '1995-07-22',
 '1995-07-23',
 '1995-07-24',
 '1995-07-25',
 '1997-07-12',
 '1997-07-13',
 '1997-07-14',
 '1999-07-01',
 '1999-07-02',
 '1999-07-03',
 '2001-08-03',
 '2001-08-04',
 '2001-08-05',
 '2001-08-06',
 '2002-07-01',
 '2002-07-02',
 '2005-08-11',
 '2005-08-12',
 '2006-07-29',
 '2006-07-30',
 '2006-07-31',
 '2010-07-02',
 '2010-07-03',
 '2010-07-04',
 '2010-07-14',
 '2010-07-15',
 '2011-07-17',
 '2011-07-18',
 '2011-07-19',
 '2011-07-20',
 '2013-07-04',
 '2013-07-05',
 '2013-07-12',
 '2013-07-13',
 '2013-07-16',
 '2013-07-17',
 '2015-07-17',
 '2015-07-18',
 '2015-07-26',
 '2015-07-27',
 '2016-08-04',
 '2016-08-05',
 '2016-08-06',
 '2016-08-07',
 '2016-08-08',
 '2016-08-09',
 '2017-07-16',
 '2017-07-17',
 '2017-07-18',
 '2018-06-28',
 '2018-06-29',
 '2018-06-30',
 '2018-08-03',
 '2018-08-04',
 '2018-08-05',
 '2018-08-26',
 '2018-08-27',
 '2018-09-01',
 '2018-09-02']

In [32]:
synpuf_visit_occurence_filtered_CONTROL = pd.read_sql_query('''SELECT * FROM synpuf5.visit_occurrence WHERE visit_start_date in %s''' % str(tuple(list_of_dates_control)), cnx)
synpuf_visit_occurence_filtered_CONTROL

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id
0,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0
1,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0
2,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0
3,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0
4,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0
5,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0
6,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0
7,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0
8,4392,88,9202,2010-07-14,None,2010-08-03,None,44818517,3710.0,2606.0,542292281173667,4391.0
9,4590,90,9201,2010-07-03,None,2010-07-12,None,44818517,3837.0,2680.0,196721177025054,4589.0
10,4894,95,0,2010-07-04,None,2010-07-04,None,44818517,4106.0,2876.0,887053389071481,4893.0
11,4979,95,0,2010-07-04,None,2010-07-07,None,44818517,4186.0,2903.0,887683386177149,4978.0
12,5059,96,0,2010-07-04,None,2010-07-04,None,44818517,4257.0,2953.0,887133387783075,5058.0
13,5620,105,0,2010-07-14,None,2010-07-14,None,44818517,4684.0,3253.0,887103385638620,5619.0
14,5631,105,0,2010-07-03,None,2010-07-03,None,44818517,4681.0,3250.0,887163389303558,5630.0
15,6392,123,0,2010-07-03,None,2010-07-04,None,44818517,5306.0,3658.0,887153387179463,6391.0
16,6257,117,0,2010-07-14,None,2010-07-14,None,44818517,5191.0,3574.0,887393388732386,6256.0
17,7402,147,0,2010-07-03,None,2010-07-03,None,44818517,6119.0,4173.0,887723387392321,7401.0
18,7038,138,0,2010-07-14,None,2010-07-14,None,44818517,5821.0,3954.0,887023387075656,7037.0
19,7085,138,0,2010-07-14,None,2010-07-14,None,44818517,5854.0,3973.0,887673386763192,7084.0
20,7416,148,9202,2010-07-02,None,2010-07-02,None,44818517,6133.0,4181.0,542032280838912,7415.0
21,9439,185,0,2010-07-15,None,2010-07-17,None,44818517,7796.0,5253.0,887283389521987,9438.0
22,7850,153,0,2010-07-04,None,2010-07-04,None,44818517,6517.0,4419.0,887963386287919,7849.0
23,7787,152,0,2010-07-15,None,2010-07-15,None,44818517,6467.0,4383.0,887303384760140,7786.0
24,8047,159,0,2010-07-04,None,2010-07-04,None,44818517,6681.0,4528.0,887313388972099,8046.0
25,10808,213,0,2010-07-14,None,2010-07-14,None,44818517,7191.0,4852.0,887663388737647,10807.0
26,10219,199,0,2010-07-04,None,2010-07-13,None,44818517,251.0,163.0,887013386778490,10218.0
27,10220,199,0,2010-07-04,None,2010-07-04,None,44818517,5422.0,2968.0,887033386325779,10219.0
28,10428,205,9202,2010-07-03,None,2010-07-03,None,44818517,5809.0,3947.0,542012281274554,NaN
29,11672,226,0,2010-07-02,None,2010-07-02,None,44818517,9459.0,6343.0,887393385849060,11671.0
...,...,...,...,...,...,...,...,...,...,...,...,...
18722,5571254,116177,9202,2010-07-04,None,2010-07-04,None,44818517,54608.0,11958.0,542432281271830,5571253.0
18723,5571258,116177,0,2010-07-03,None,2010-07-03,None,44818517,71245.0,38122.0,887103386003597,5571257.0
18724,5572528,116205,0,2010-07-03,None,2010-07-03,None,44818517,76056.0,40217.0,887413388617167,5572527.0
18725,5572967,116215,0,2010-07-02,None,2010-07-02,None,44818517,485990.0,32209.0,887063387062858,5572966.0
18726,5573639,116230,0,2010-07-14,None,2010-07-14,None,44818517,18240.0,4517.0,887453386500436,5573638.0
18727,5574128,116235,0,2010-07-15,None,2010-07-15,None,44818517,54255.0,9183.0,887523388338987,5574127.0
18728,5574428,116240,0,2010-07-03,None,2010-07-03,None,44818517,21853.0,3745.0,887643389013204,5574427.0
18729,5574655,116246,0,2010-07-14,None,2010-07-14,None,44818517,635326.0,82032.0,887503385105058,5574654.0
18730,5574820,116250,0,2010-07-14,None,2010-07-14,None,44818517,215440.0,50001.0,887803388835576,5574819.0
18731,5574855,116252,0,2010-07-04,None,2010-07-04,None,44818517,193724.0,88365.0,887863387318576,5574854.0
18732,5575311,116259,0,2010-07-03,None,2010-07-03,None,44818517,45.0,40.0,887763387563768,5575310.0
18733,5575679,116267,0,2010-07-02,None,2010-07-02,None,44818517,16.0,13.0,887703384903838,5575678.0
18734,5575938,116273,9202,2010-07-02,None,2010-07-03,None,44818517,52085.0,39896.0,542122281100325,5575937.0
18735,5575955,116273,9202,2010-07-03,None,2010-07-03,None,44818517,273279.0,117988.0,542502281303322,5575954.0
18736,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0
18737,5576106,116274,0,2010-07-02,None,2010-07-02,None,44818517,90282.0,46631.0,887543385123548,5576105.0
18738,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0
18739,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0
18740,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0
18741,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0
18742,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0
18743,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0
18744,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0
18745,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0
18746,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0
18747,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0
18748,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0
18749,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0
18750,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0
18751,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0

In [33]:
synpuf_visit_occurence_filtered_CONTROL_with_age = synpuf_visit_occurence_filtered_CONTROL.merge(synpuf_person[list(('person_id','year_of_birth'))])

synpuf_visit_occurence_filtered_CONTROL_with_age.visit_start_date = pd.to_datetime(synpuf_visit_occurence_filtered_CONTROL_with_age['visit_start_date'])
synpuf_visit_occurence_filtered_CONTROL_with_age['admit_year'] =  pd.DatetimeIndex(synpuf_visit_occurence_filtered_CONTROL_with_age['visit_start_date']).year
synpuf_visit_occurence_filtered_CONTROL_with_age['patient_age'] = synpuf_visit_occurence_filtered_CONTROL_with_age['admit_year'] - synpuf_visit_occurence_filtered_CONTROL_with_age['year_of_birth']

synpuf_visit_occurence_filtered_CONTROL_with_age

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age
0,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0,1922,2010,88
1,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0,1929,2010,81
2,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0,1965,2010,45
3,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0,1940,2010,70
4,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0,1922,2010,88
5,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0,1922,2010,88
6,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0,1957,2010,53
7,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0,1963,2010,47
8,4392,88,9202,2010-07-14,None,2010-08-03,None,44818517,3710.0,2606.0,542292281173667,4391.0,1922,2010,88
9,4590,90,9201,2010-07-03,None,2010-07-12,None,44818517,3837.0,2680.0,196721177025054,4589.0,1925,2010,85
10,4894,95,0,2010-07-04,None,2010-07-04,None,44818517,4106.0,2876.0,887053389071481,4893.0,1931,2010,79
11,4979,95,0,2010-07-04,None,2010-07-07,None,44818517,4186.0,2903.0,887683386177149,4978.0,1931,2010,79
12,5059,96,0,2010-07-04,None,2010-07-04,None,44818517,4257.0,2953.0,887133387783075,5058.0,1934,2010,76
13,5620,105,0,2010-07-14,None,2010-07-14,None,44818517,4684.0,3253.0,887103385638620,5619.0,1926,2010,84
14,5631,105,0,2010-07-03,None,2010-07-03,None,44818517,4681.0,3250.0,887163389303558,5630.0,1926,2010,84
15,6392,123,0,2010-07-03,None,2010-07-04,None,44818517,5306.0,3658.0,887153387179463,6391.0,1967,2010,43
16,6257,117,0,2010-07-14,None,2010-07-14,None,44818517,5191.0,3574.0,887393388732386,6256.0,1937,2010,73
17,7402,147,0,2010-07-03,None,2010-07-03,None,44818517,6119.0,4173.0,887723387392321,7401.0,1926,2010,84
18,7038,138,0,2010-07-14,None,2010-07-14,None,44818517,5821.0,3954.0,887023387075656,7037.0,1934,2010,76
19,7085,138,0,2010-07-14,None,2010-07-14,None,44818517,5854.0,3973.0,887673386763192,7084.0,1934,2010,76
20,7416,148,9202,2010-07-02,None,2010-07-02,None,44818517,6133.0,4181.0,542032280838912,7415.0,1947,2010,63
21,9439,185,0,2010-07-15,None,2010-07-17,None,44818517,7796.0,5253.0,887283389521987,9438.0,1919,2010,91
22,7850,153,0,2010-07-04,None,2010-07-04,None,44818517,6517.0,4419.0,887963386287919,7849.0,1941,2010,69
23,7787,152,0,2010-07-15,None,2010-07-15,None,44818517,6467.0,4383.0,887303384760140,7786.0,1927,2010,83
24,8047,159,0,2010-07-04,None,2010-07-04,None,44818517,6681.0,4528.0,887313388972099,8046.0,1931,2010,79
25,10808,213,0,2010-07-14,None,2010-07-14,None,44818517,7191.0,4852.0,887663388737647,10807.0,1940,2010,70
26,10219,199,0,2010-07-04,None,2010-07-13,None,44818517,251.0,163.0,887013386778490,10218.0,1924,2010,86
27,10220,199,0,2010-07-04,None,2010-07-04,None,44818517,5422.0,2968.0,887033386325779,10219.0,1924,2010,86
28,10428,205,9202,2010-07-03,None,2010-07-03,None,44818517,5809.0,3947.0,542012281274554,NaN,1939,2010,71
29,11672,226,0,2010-07-02,None,2010-07-02,None,44818517,9459.0,6343.0,887393385849060,11671.0,1936,2010,74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18722,5571254,116177,9202,2010-07-04,None,2010-07-04,None,44818517,54608.0,11958.0,542432281271830,5571253.0,1939,2010,71
18723,5571258,116177,0,2010-07-03,None,2010-07-03,None,44818517,71245.0,38122.0,887103386003597,5571257.0,1939,2010,71
18724,5572528,116205,0,2010-07-03,None,2010-07-03,None,44818517,76056.0,40217.0,887413388617167,5572527.0,1914,2010,96
18725,5572967,116215,0,2010-07-02,None,2010-07-02,None,44818517,485990.0,32209.0,887063387062858,5572966.0,1938,2010,72
18726,5573639,116230,0,2010-07-14,None,2010-07-14,None,44818517,18240.0,4517.0,887453386500436,5573638.0,1942,2010,68
18727,5574128,116235,0,2010-07-15,None,2010-07-15,None,44818517,54255.0,9183.0,887523388338987,5574127.0,1946,2010,64
18728,5574428,116240,0,2010-07-03,None,2010-07-03,None,44818517,21853.0,3745.0,887643389013204,5574427.0,1926,2010,84
18729,5574655,116246,0,2010-07-14,None,2010-07-14,None,44818517,635326.0,82032.0,887503385105058,5574654.0,1939,2010,71
18730,5574820,116250,0,2010-07-14,None,2010-07-14,None,44818517,215440.0,50001.0,887803388835576,5574819.0,1968,2010,42
18731,5574855,116252,0,2010-07-04,None,2010-07-04,None,44818517,193724.0,88365.0,887863387318576,5574854.0,1939,2010,71
18732,5575311,116259,0,2010-07-03,None,2010-07-03,None,44818517,45.0,40.0,887763387563768,5575310.0,1927,2010,83
18733,5575679,116267,0,2010-07-02,None,2010-07-02,None,44818517,16.0,13.0,887703384903838,5575678.0,1956,2010,54
18734,5575938,116273,9202,2010-07-02,None,2010-07-03,None,44818517,52085.0,39896.0,542122281100325,5575937.0,1924,2010,86
18735,5575955,116273,9202,2010-07-03,None,2010-07-03,None,44818517,273279.0,117988.0,542502281303322,5575954.0,1924,2010,86
18736,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0,1943,2010,67
18737,5576106,116274,0,2010-07-02,None,2010-07-02,None,44818517,90282.0,46631.0,887543385123548,5576105.0,1941,2010,69
18738,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0,1954,2010,56
18739,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0,1953,2010,57
18740,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0,1953,2010,57
18741,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0,1940,2010,70
18742,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0,1930,2010,80
18743,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0,1960,2010,50
18744,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0,1953,2010,57
18745,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0,1956,2010,54
18746,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0,1925,2010,85
18747,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0,1920,2010,90
18748,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0,1941,2010,69
18749,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0,1940,2010,70
18750,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0,1935,2010,75
18751,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0,1916,2010,94

In [34]:
synpuf_visit_occurence_filtered_CONTROL_with_age = synpuf_visit_occurence_filtered_CONTROL_with_age.assign(
    Age_Slot = pd.cut(
        synpuf_visit_occurence_filtered_CONTROL_with_age.patient_age,
        [0,10,20,30,40,50,60,70,80,90,100],
        labels=['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100']))

synpuf_visit_occurence_filtered_CONTROL_with_age

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age,Age_Slot
0,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0,1922,2010,88,80-90
1,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0,1929,2010,81,80-90
2,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0,1965,2010,45,40-50
3,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0,1940,2010,70,60-70
4,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0,1922,2010,88,80-90
5,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0,1922,2010,88,80-90
6,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0,1957,2010,53,50-60
7,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0,1963,2010,47,40-50
8,4392,88,9202,2010-07-14,None,2010-08-03,None,44818517,3710.0,2606.0,542292281173667,4391.0,1922,2010,88,80-90
9,4590,90,9201,2010-07-03,None,2010-07-12,None,44818517,3837.0,2680.0,196721177025054,4589.0,1925,2010,85,80-90
10,4894,95,0,2010-07-04,None,2010-07-04,None,44818517,4106.0,2876.0,887053389071481,4893.0,1931,2010,79,70-80
11,4979,95,0,2010-07-04,None,2010-07-07,None,44818517,4186.0,2903.0,887683386177149,4978.0,1931,2010,79,70-80
12,5059,96,0,2010-07-04,None,2010-07-04,None,44818517,4257.0,2953.0,887133387783075,5058.0,1934,2010,76,70-80
13,5620,105,0,2010-07-14,None,2010-07-14,None,44818517,4684.0,3253.0,887103385638620,5619.0,1926,2010,84,80-90
14,5631,105,0,2010-07-03,None,2010-07-03,None,44818517,4681.0,3250.0,887163389303558,5630.0,1926,2010,84,80-90
15,6392,123,0,2010-07-03,None,2010-07-04,None,44818517,5306.0,3658.0,887153387179463,6391.0,1967,2010,43,40-50
16,6257,117,0,2010-07-14,None,2010-07-14,None,44818517,5191.0,3574.0,887393388732386,6256.0,1937,2010,73,70-80
17,7402,147,0,2010-07-03,None,2010-07-03,None,44818517,6119.0,4173.0,887723387392321,7401.0,1926,2010,84,80-90
18,7038,138,0,2010-07-14,None,2010-07-14,None,44818517,5821.0,3954.0,887023387075656,7037.0,1934,2010,76,70-80
19,7085,138,0,2010-07-14,None,2010-07-14,None,44818517,5854.0,3973.0,887673386763192,7084.0,1934,2010,76,70-80
20,7416,148,9202,2010-07-02,None,2010-07-02,None,44818517,6133.0,4181.0,542032280838912,7415.0,1947,2010,63,60-70
21,9439,185,0,2010-07-15,None,2010-07-17,None,44818517,7796.0,5253.0,887283389521987,9438.0,1919,2010,91,90-100
22,7850,153,0,2010-07-04,None,2010-07-04,None,44818517,6517.0,4419.0,887963386287919,7849.0,1941,2010,69,60-70
23,7787,152,0,2010-07-15,None,2010-07-15,None,44818517,6467.0,4383.0,887303384760140,7786.0,1927,2010,83,80-90
24,8047,159,0,2010-07-04,None,2010-07-04,None,44818517,6681.0,4528.0,887313388972099,8046.0,1931,2010,79,70-80
25,10808,213,0,2010-07-14,None,2010-07-14,None,44818517,7191.0,4852.0,887663388737647,10807.0,1940,2010,70,60-70
26,10219,199,0,2010-07-04,None,2010-07-13,None,44818517,251.0,163.0,887013386778490,10218.0,1924,2010,86,80-90
27,10220,199,0,2010-07-04,None,2010-07-04,None,44818517,5422.0,2968.0,887033386325779,10219.0,1924,2010,86,80-90
28,10428,205,9202,2010-07-03,None,2010-07-03,None,44818517,5809.0,3947.0,542012281274554,NaN,1939,2010,71,70-80
29,11672,226,0,2010-07-02,None,2010-07-02,None,44818517,9459.0,6343.0,887393385849060,11671.0,1936,2010,74,70-80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18722,5571254,116177,9202,2010-07-04,None,2010-07-04,None,44818517,54608.0,11958.0,542432281271830,5571253.0,1939,2010,71,70-80
18723,5571258,116177,0,2010-07-03,None,2010-07-03,None,44818517,71245.0,38122.0,887103386003597,5571257.0,1939,2010,71,70-80
18724,5572528,116205,0,2010-07-03,None,2010-07-03,None,44818517,76056.0,40217.0,887413388617167,5572527.0,1914,2010,96,90-100
18725,5572967,116215,0,2010-07-02,None,2010-07-02,None,44818517,485990.0,32209.0,887063387062858,5572966.0,1938,2010,72,70-80
18726,5573639,116230,0,2010-07-14,None,2010-07-14,None,44818517,18240.0,4517.0,887453386500436,5573638.0,1942,2010,68,60-70
18727,5574128,116235,0,2010-07-15,None,2010-07-15,None,44818517,54255.0,9183.0,887523388338987,5574127.0,1946,2010,64,60-70
18728,5574428,116240,0,2010-07-03,None,2010-07-03,None,44818517,21853.0,3745.0,887643389013204,5574427.0,1926,2010,84,80-90
18729,5574655,116246,0,2010-07-14,None,2010-07-14,None,44818517,635326.0,82032.0,887503385105058,5574654.0,1939,2010,71,70-80
18730,5574820,116250,0,2010-07-14,None,2010-07-14,None,44818517,215440.0,50001.0,887803388835576,5574819.0,1968,2010,42,40-50
18731,5574855,116252,0,2010-07-04,None,2010-07-04,None,44818517,193724.0,88365.0,887863387318576,5574854.0,1939,2010,71,70-80
18732,5575311,116259,0,2010-07-03,None,2010-07-03,None,44818517,45.0,40.0,887763387563768,5575310.0,1927,2010,83,80-90
18733,5575679,116267,0,2010-07-02,None,2010-07-02,None,44818517,16.0,13.0,887703384903838,5575678.0,1956,2010,54,50-60
18734,5575938,116273,9202,2010-07-02,None,2010-07-03,None,44818517,52085.0,39896.0,542122281100325,5575937.0,1924,2010,86,80-90
18735,5575955,116273,9202,2010-07-03,None,2010-07-03,None,44818517,273279.0,117988.0,542502281303322,5575954.0,1924,2010,86,80-90
18736,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0,1943,2010,67,60-70
18737,5576106,116274,0,2010-07-02,None,2010-07-02,None,44818517,90282.0,46631.0,887543385123548,5576105.0,1941,2010,69,60-70
18738,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0,1954,2010,56,50-60
18739,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0,1953,2010,57,50-60
18740,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0,1953,2010,57,50-60
18741,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0,1940,2010,70,60-70
18742,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0,1930,2010,80,70-80
18743,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0,1960,2010,50,40-50
18744,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0,1953,2010,57,50-60
18745,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0,1956,2010,54,50-60
18746,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0,1925,2010,85,80-90
18747,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0,1920,2010,90,80-90
18748,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0,1941,2010,69,60-70
18749,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0,1940,2010,70,60-70
18750,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0,1935,2010,75,70-80
18751,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0,1916,2010,94,90-100

## synpuf_visit_occurence_filtered CONTROL_7 days

In [35]:
# Below is the list of the dates from the Final heat wave case days
list_of_dates_control_7 = weather_data_ctrl_immediate_days_7['DateTime'].tolist()
list_of_dates_control_7

['1991-07-13',
 '1991-07-14',
 '1991-07-15',
 '1991-07-16',
 '1991-07-17',
 '1991-07-18',
 '1991-07-19',
 '1993-06-30',
 '1993-07-01',
 '1993-07-02',
 '1993-07-03',
 '1993-07-04',
 '1993-07-05',
 '1993-07-06',
 '1994-07-01',
 '1994-07-02',
 '1994-07-03',
 '1994-07-04',
 '1994-07-05',
 '1994-07-06',
 '1994-07-07',
 '1995-07-07',
 '1995-07-08',
 '1995-07-09',
 '1995-07-10',
 '1995-07-11',
 '1995-07-12',
 '1995-07-13',
 '1995-07-19',
 '1995-07-20',
 '1995-07-21',
 '1995-07-22',
 '1995-07-23',
 '1995-07-24',
 '1995-07-25',
 '1997-07-08',
 '1997-07-09',
 '1997-07-10',
 '1997-07-11',
 '1997-07-12',
 '1997-07-13',
 '1997-07-14',
 '1999-06-27',
 '1999-06-28',
 '1999-06-29',
 '1999-06-30',
 '1999-07-01',
 '1999-07-02',
 '1999-07-03',
 '2001-07-31',
 '2001-08-01',
 '2001-08-02',
 '2001-08-03',
 '2001-08-04',
 '2001-08-05',
 '2001-08-06',
 '2002-06-26',
 '2002-06-27',
 '2002-06-28',
 '2002-06-29',
 '2002-06-30',
 '2002-07-01',
 '2002-07-02',
 '2005-08-06',
 '2005-08-07',
 '2005-08-08',
 '2005-08-09',
 '2005-08-10',
 '2005-08-11',
 '2005-08-12',
 '2006-07-25',
 '2006-07-26',
 '2006-07-27',
 '2006-07-28',
 '2006-07-29',
 '2006-07-30',
 '2006-07-31',
 '2010-06-28',
 '2010-06-29',
 '2010-06-30',
 '2010-07-01',
 '2010-07-02',
 '2010-07-03',
 '2010-07-04',
 '2010-07-09',
 '2010-07-10',
 '2010-07-11',
 '2010-07-12',
 '2010-07-13',
 '2010-07-14',
 '2010-07-15',
 '2011-07-14',
 '2011-07-15',
 '2011-07-16',
 '2011-07-17',
 '2011-07-18',
 '2011-07-19',
 '2011-07-20',
 '2013-06-29',
 '2013-06-30',
 '2013-07-01',
 '2013-07-02',
 '2013-07-03',
 '2013-07-04',
 '2013-07-05',
 '2013-07-08',
 '2013-07-09',
 '2013-07-10',
 '2013-07-11',
 '2013-07-12',
 '2013-07-13',
 '2013-07-11',
 '2013-07-12',
 '2013-07-13',
 '2013-07-16',
 '2013-07-17',
 '2015-07-12',
 '2015-07-13',
 '2015-07-14',
 '2015-07-15',
 '2015-07-16',
 '2015-07-17',
 '2015-07-18',
 '2015-07-21',
 '2015-07-22',
 '2015-07-23',
 '2015-07-24',
 '2015-07-25',
 '2015-07-26',
 '2015-07-27',
 '2016-08-03',
 '2016-08-04',
 '2016-08-05',
 '2016-08-06',
 '2016-08-07',
 '2016-08-08',
 '2016-08-09',
 '2017-07-12',
 '2017-07-13',
 '2017-07-14',
 '2017-07-15',
 '2017-07-16',
 '2017-07-17',
 '2017-07-18',
 '2018-06-24',
 '2018-06-25',
 '2018-06-26',
 '2018-06-27',
 '2018-06-28',
 '2018-06-29',
 '2018-06-30',
 '2018-07-30',
 '2018-07-31',
 '2018-08-01',
 '2018-08-02',
 '2018-08-03',
 '2018-08-04',
 '2018-08-05',
 '2018-08-21',
 '2018-08-22',
 '2018-08-23',
 '2018-08-24',
 '2018-08-25',
 '2018-08-26',
 '2018-08-27',
 '2018-08-27',
 '2018-08-30',
 '2018-08-31',
 '2018-09-01',
 '2018-09-02']

In [36]:
synpuf_visit_occurence_filtered_CONTROL_7 = pd.read_sql_query('''SELECT * FROM synpuf5.visit_occurrence WHERE visit_start_date in %s''' % str(tuple(list_of_dates_control_7)), cnx)
synpuf_visit_occurence_filtered_CONTROL_7

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id
0,197,7,0,2010-06-30,None,2010-06-30,None,44818517,184.0,123.0,887603388331968,196.0
1,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0
2,314,9,0,2010-06-30,None,2010-06-30,None,44818517,282.0,185.0,887953387448581,313.0
3,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0
4,845,17,0,2010-07-13,None,2010-07-13,None,44818517,685.0,447.0,887493386504937,844.0
5,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0
6,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0
7,1576,30,0,2010-07-13,None,2010-07-13,None,44818517,1283.0,811.0,887813384786162,1575.0
8,1585,30,0,2010-07-11,None,2010-07-11,None,44818517,1324.0,846.0,887913387157124,1584.0
9,1856,35,0,2010-06-30,None,2010-06-30,None,44818517,1575.0,1034.0,887653386973011,1855.0
10,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0
11,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0
12,2205,43,9202,2010-07-01,None,2010-07-03,None,44818517,1870.0,1215.0,542392281641264,2204.0
13,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0
14,2342,46,0,2010-07-13,None,2010-07-13,None,44818517,1982.0,1303.0,887653388088882,2341.0
15,2552,54,0,2010-07-12,None,2010-07-12,None,44818517,2168.0,1409.0,887593388232119,2551.0
16,2775,60,0,2010-07-01,None,2010-07-01,None,44818517,2367.0,1559.0,887503385413543,2774.0
17,3213,68,9202,2010-07-10,None,2010-07-10,None,44818517,2747.0,1860.0,542942281155526,3212.0
18,3300,68,0,2010-06-28,None,2010-06-28,None,44818517,2810.0,1873.0,887733387116633,3299.0
19,3360,70,0,2010-07-13,None,2010-07-13,None,44818517,2856.0,1933.0,887933388739623,3359.0
20,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0
21,3525,73,0,2010-07-10,None,2010-07-10,None,44818517,2999.0,2067.0,887473387337342,3524.0
22,3548,74,9202,2010-07-12,None,2010-07-12,None,44818517,3019.0,2086.0,542692281353211,3547.0
23,3601,76,9202,2010-06-28,None,2010-06-28,None,44818517,3062.0,2037.0,542582281548183,3600.0
24,3874,81,0,2010-07-09,None,2010-07-09,None,44818517,300.0,200.0,887573386720223,3873.0
25,3865,81,0,2010-07-10,None,2010-07-10,None,44818517,3279.0,2284.0,887343385743096,3864.0
26,4346,86,0,2010-07-11,None,2010-07-11,None,44818517,3671.0,2534.0,887763386824993,4345.0
27,4181,85,0,2010-07-09,None,2010-07-09,None,44818517,136.0,94.0,887233386128643,4180.0
28,4589,90,9201,2010-07-10,None,2010-07-15,None,44818517,3836.0,2679.0,196121176990349,NaN
29,4392,88,9202,2010-07-14,None,2010-08-03,None,44818517,3710.0,2606.0,542292281173667,4391.0
...,...,...,...,...,...,...,...,...,...,...,...,...
52558,5576588,116285,0,2010-07-10,None,2010-07-10,None,44818517,134390.0,65067.0,887753388082042,5576587.0
52559,5576657,116286,0,2010-06-30,None,2010-06-30,None,44818517,276661.0,119260.0,887713387509358,5576656.0
52560,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0
52561,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0
52562,5576706,116288,9201,2010-07-09,None,2010-07-10,None,44818517,3683.0,670.0,196931176976105,NaN
52563,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0
52564,5576959,116292,0,2010-06-28,None,2010-06-28,None,44818517,89783.0,49049.0,887223388420198,5576958.0
52565,5576973,116292,0,2010-07-12,None,2010-07-12,None,44818517,634337.0,238815.0,887633384912121,5576972.0
52566,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0
52567,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0
52568,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0
52569,5576932,116291,0,2010-07-10,None,2010-07-10,None,44818517,142000.0,68057.0,887883388564937,5576931.0
52570,5577950,116314,0,2010-06-28,None,2010-06-28,None,44818517,97963.0,49827.0,887483388653416,5577949.0
52571,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0
52572,5577559,116303,0,2010-07-13,None,2010-07-13,None,44818517,10301.0,6832.0,887823385688854,5577558.0
52573,5577847,116311,0,2010-06-28,None,2010-06-28,None,44818517,396232.0,114841.0,887133385017307,5577846.0
52574,5577990,116314,0,2010-06-30,None,2010-06-30,None,44818517,5.0,5.0,887933389547980,5577989.0
52575,5578248,116322,0,2010-07-10,None,2010-07-19,None,44818517,479195.0,54562.0,887453387433693,5578247.0
52576,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0
52577,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0
52578,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0
52579,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0
52580,5578823,116337,0,2010-07-09,None,2010-07-09,None,44818517,250792.0,109740.0,887863384973051,5578822.0
52581,5578897,116339,0,2010-07-10,None,2010-07-10,None,44818517,7262.0,26484.0,887083387666641,5578896.0
52582,5579156,116342,0,2010-07-13,None,2010-07-13,None,44818517,91766.0,45530.0,887103388905386,5579155.0
52583,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0
52584,5579332,116347,0,2010-07-09,None,2010-07-09,None,44818517,196780.0,89555.0,887523388182751,5579331.0
52585,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0
52586,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0
52587,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0

In [37]:
synpuf_visit_occurence_filtered_CONTROL_with_age_7 = synpuf_visit_occurence_filtered_CONTROL_7.merge(synpuf_person[list(('person_id','year_of_birth'))])

synpuf_visit_occurence_filtered_CONTROL_with_age_7.visit_start_date = pd.to_datetime(synpuf_visit_occurence_filtered_CONTROL_with_age_7['visit_start_date'])
synpuf_visit_occurence_filtered_CONTROL_with_age_7['admit_year'] =  pd.DatetimeIndex(synpuf_visit_occurence_filtered_CONTROL_with_age_7['visit_start_date']).year
synpuf_visit_occurence_filtered_CONTROL_with_age_7['patient_age'] = synpuf_visit_occurence_filtered_CONTROL_with_age_7['admit_year'] - synpuf_visit_occurence_filtered_CONTROL_with_age_7['year_of_birth']

synpuf_visit_occurence_filtered_CONTROL_with_age_7

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age
0,197,7,0,2010-06-30,None,2010-06-30,None,44818517,184.0,123.0,887603388331968,196.0,1922,2010,88
1,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0,1922,2010,88
2,314,9,0,2010-06-30,None,2010-06-30,None,44818517,282.0,185.0,887953387448581,313.0,1976,2010,34
3,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0,1929,2010,81
4,845,17,0,2010-07-13,None,2010-07-13,None,44818517,685.0,447.0,887493386504937,844.0,1919,2010,91
5,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0,1965,2010,45
6,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0,1940,2010,70
7,1576,30,0,2010-07-13,None,2010-07-13,None,44818517,1283.0,811.0,887813384786162,1575.0,1959,2010,51
8,1585,30,0,2010-07-11,None,2010-07-11,None,44818517,1324.0,846.0,887913387157124,1584.0,1959,2010,51
9,1856,35,0,2010-06-30,None,2010-06-30,None,44818517,1575.0,1034.0,887653386973011,1855.0,1911,2010,99
10,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0,1922,2010,88
11,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0,1922,2010,88
12,2205,43,9202,2010-07-01,None,2010-07-03,None,44818517,1870.0,1215.0,542392281641264,2204.0,1941,2010,69
13,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0,1957,2010,53
14,2342,46,0,2010-07-13,None,2010-07-13,None,44818517,1982.0,1303.0,887653388088882,2341.0,1931,2010,79
15,2552,54,0,2010-07-12,None,2010-07-12,None,44818517,2168.0,1409.0,887593388232119,2551.0,1931,2010,79
16,2775,60,0,2010-07-01,None,2010-07-01,None,44818517,2367.0,1559.0,887503385413543,2774.0,1925,2010,85
17,3213,68,9202,2010-07-10,None,2010-07-10,None,44818517,2747.0,1860.0,542942281155526,3212.0,1954,2010,56
18,3300,68,0,2010-06-28,None,2010-06-28,None,44818517,2810.0,1873.0,887733387116633,3299.0,1954,2010,56
19,3360,70,0,2010-07-13,None,2010-07-13,None,44818517,2856.0,1933.0,887933388739623,3359.0,1923,2010,87
20,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0,1963,2010,47
21,3525,73,0,2010-07-10,None,2010-07-10,None,44818517,2999.0,2067.0,887473387337342,3524.0,1925,2010,85
22,3548,74,9202,2010-07-12,None,2010-07-12,None,44818517,3019.0,2086.0,542692281353211,3547.0,1924,2010,86
23,3601,76,9202,2010-06-28,None,2010-06-28,None,44818517,3062.0,2037.0,542582281548183,3600.0,1938,2010,72
24,3874,81,0,2010-07-09,None,2010-07-09,None,44818517,300.0,200.0,887573386720223,3873.0,1940,2010,70
25,3865,81,0,2010-07-10,None,2010-07-10,None,44818517,3279.0,2284.0,887343385743096,3864.0,1940,2010,70
26,4346,86,0,2010-07-11,None,2010-07-11,None,44818517,3671.0,2534.0,887763386824993,4345.0,1926,2010,84
27,4181,85,0,2010-07-09,None,2010-07-09,None,44818517,136.0,94.0,887233386128643,4180.0,1937,2010,73
28,4589,90,9201,2010-07-10,None,2010-07-15,None,44818517,3836.0,2679.0,196121176990349,NaN,1925,2010,85
29,4590,90,9201,2010-07-03,None,2010-07-12,None,44818517,3837.0,2680.0,196721177025054,4589.0,1925,2010,85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52558,5576588,116285,0,2010-07-10,None,2010-07-10,None,44818517,134390.0,65067.0,887753388082042,5576587.0,1954,2010,56
52559,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0,1954,2010,56
52560,5576657,116286,0,2010-06-30,None,2010-06-30,None,44818517,276661.0,119260.0,887713387509358,5576656.0,1927,2010,83
52561,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0,1953,2010,57
52562,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0,1953,2010,57
52563,5576706,116288,9201,2010-07-09,None,2010-07-10,None,44818517,3683.0,670.0,196931176976105,NaN,1953,2010,57
52564,5576959,116292,0,2010-06-28,None,2010-06-28,None,44818517,89783.0,49049.0,887223388420198,5576958.0,1930,2010,80
52565,5576973,116292,0,2010-07-12,None,2010-07-12,None,44818517,634337.0,238815.0,887633384912121,5576972.0,1930,2010,80
52566,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0,1930,2010,80
52567,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0,1943,2010,67
52568,5576932,116291,0,2010-07-10,None,2010-07-10,None,44818517,142000.0,68057.0,887883388564937,5576931.0,1943,2010,67
52569,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0,1940,2010,70
52570,5577559,116303,0,2010-07-13,None,2010-07-13,None,44818517,10301.0,6832.0,887823385688854,5577558.0,1940,2010,70
52571,5577950,116314,0,2010-06-28,None,2010-06-28,None,44818517,97963.0,49827.0,887483388653416,5577949.0,1934,2010,76
52572,5577990,116314,0,2010-06-30,None,2010-06-30,None,44818517,5.0,5.0,887933389547980,5577989.0,1934,2010,76
52573,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0,1960,2010,50
52574,5577847,116311,0,2010-06-28,None,2010-06-28,None,44818517,396232.0,114841.0,887133385017307,5577846.0,1960,2010,50
52575,5578248,116322,0,2010-07-10,None,2010-07-19,None,44818517,479195.0,54562.0,887453387433693,5578247.0,1951,2010,59
52576,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0,1956,2010,54
52577,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0,1953,2010,57
52578,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0,1925,2010,85
52579,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0,1940,2010,70
52580,5578823,116337,0,2010-07-09,None,2010-07-09,None,44818517,250792.0,109740.0,887863384973051,5578822.0,1940,2010,70
52581,5578897,116339,0,2010-07-10,None,2010-07-10,None,44818517,7262.0,26484.0,887083387666641,5578896.0,1920,2010,90
52582,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0,1920,2010,90
52583,5579156,116342,0,2010-07-13,None,2010-07-13,None,44818517,91766.0,45530.0,887103388905386,5579155.0,1930,2010,80
52584,5579332,116347,0,2010-07-09,None,2010-07-09,None,44818517,196780.0,89555.0,887523388182751,5579331.0,1939,2010,71
52585,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0,1941,2010,69
52586,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0,1916,2010,94
52587,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0,1935,2010,75

In [38]:
synpuf_visit_occurence_filtered_CONTROL_with_age_7 = synpuf_visit_occurence_filtered_CONTROL_with_age_7.assign(
    Age_Slot = pd.cut(
        synpuf_visit_occurence_filtered_CONTROL_with_age_7.patient_age,
        [0,10,20,30,40,50,60,70,80,90,100],
        labels=['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100']))

synpuf_visit_occurence_filtered_CONTROL_with_age_7

,visit_occurrence_id,person_id,visit_concept_id,visit_start_date,visit_start_time,visit_end_date,visit_end_time,visit_type_concept_id,provider_id,care_site_id,visit_source_value,visit_source_concept_id,year_of_birth,admit_year,patient_age,Age_Slot
0,197,7,0,2010-06-30,None,2010-06-30,None,44818517,184.0,123.0,887603388331968,196.0,1922,2010,88,80-90
1,211,7,0,2010-07-03,None,2010-07-03,None,44818517,194.0,129.0,887663387821070,210.0,1922,2010,88,80-90
2,314,9,0,2010-06-30,None,2010-06-30,None,44818517,282.0,185.0,887953387448581,313.0,1976,2010,34,30-40
3,401,12,0,2010-07-02,None,2010-07-02,None,44818517,325.0,247.0,887973386483520,400.0,1929,2010,81,80-90
4,845,17,0,2010-07-13,None,2010-07-13,None,44818517,685.0,447.0,887493386504937,844.0,1919,2010,91,90-100
5,1309,25,0,2010-07-03,None,2010-07-07,None,44818517,1091.0,696.0,887623388188771,1308.0,1965,2010,45,40-50
6,1363,27,0,2010-07-03,None,2010-07-04,None,44818517,1137.0,712.0,887513385461038,1362.0,1940,2010,70,60-70
7,1576,30,0,2010-07-13,None,2010-07-13,None,44818517,1283.0,811.0,887813384786162,1575.0,1959,2010,51,50-60
8,1585,30,0,2010-07-11,None,2010-07-11,None,44818517,1324.0,846.0,887913387157124,1584.0,1959,2010,51,50-60
9,1856,35,0,2010-06-30,None,2010-06-30,None,44818517,1575.0,1034.0,887653386973011,1855.0,1911,2010,99,90-100
10,1910,38,0,2010-07-03,None,2010-07-03,None,44818517,1623.0,1068.0,887083385466406,1909.0,1922,2010,88,80-90
11,1947,38,0,2010-07-02,None,2010-07-02,None,44818517,1651.0,1090.0,887463389461491,1946.0,1922,2010,88,80-90
12,2205,43,9202,2010-07-01,None,2010-07-03,None,44818517,1870.0,1215.0,542392281641264,2204.0,1941,2010,69,60-70
13,2257,44,0,2010-07-03,None,2010-07-03,None,44818517,1886.0,1227.0,887373387648492,2256.0,1957,2010,53,50-60
14,2342,46,0,2010-07-13,None,2010-07-13,None,44818517,1982.0,1303.0,887653388088882,2341.0,1931,2010,79,70-80
15,2552,54,0,2010-07-12,None,2010-07-12,None,44818517,2168.0,1409.0,887593388232119,2551.0,1931,2010,79,70-80
16,2775,60,0,2010-07-01,None,2010-07-01,None,44818517,2367.0,1559.0,887503385413543,2774.0,1925,2010,85,80-90
17,3213,68,9202,2010-07-10,None,2010-07-10,None,44818517,2747.0,1860.0,542942281155526,3212.0,1954,2010,56,50-60
18,3300,68,0,2010-06-28,None,2010-06-28,None,44818517,2810.0,1873.0,887733387116633,3299.0,1954,2010,56,50-60
19,3360,70,0,2010-07-13,None,2010-07-13,None,44818517,2856.0,1933.0,887933388739623,3359.0,1923,2010,87,80-90
20,3827,79,0,2010-07-02,None,2010-07-11,None,44818517,3231.0,2250.0,887483385394131,3826.0,1963,2010,47,40-50
21,3525,73,0,2010-07-10,None,2010-07-10,None,44818517,2999.0,2067.0,887473387337342,3524.0,1925,2010,85,80-90
22,3548,74,9202,2010-07-12,None,2010-07-12,None,44818517,3019.0,2086.0,542692281353211,3547.0,1924,2010,86,80-90
23,3601,76,9202,2010-06-28,None,2010-06-28,None,44818517,3062.0,2037.0,542582281548183,3600.0,1938,2010,72,70-80
24,3874,81,0,2010-07-09,None,2010-07-09,None,44818517,300.0,200.0,887573386720223,3873.0,1940,2010,70,60-70
25,3865,81,0,2010-07-10,None,2010-07-10,None,44818517,3279.0,2284.0,887343385743096,3864.0,1940,2010,70,60-70
26,4346,86,0,2010-07-11,None,2010-07-11,None,44818517,3671.0,2534.0,887763386824993,4345.0,1926,2010,84,80-90
27,4181,85,0,2010-07-09,None,2010-07-09,None,44818517,136.0,94.0,887233386128643,4180.0,1937,2010,73,70-80
28,4589,90,9201,2010-07-10,None,2010-07-15,None,44818517,3836.0,2679.0,196121176990349,NaN,1925,2010,85,80-90
29,4590,90,9201,2010-07-03,None,2010-07-12,None,44818517,3837.0,2680.0,196721177025054,4589.0,1925,2010,85,80-90
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52558,5576588,116285,0,2010-07-10,None,2010-07-10,None,44818517,134390.0,65067.0,887753388082042,5576587.0,1954,2010,56,50-60
52559,5576590,116285,0,2010-07-15,None,2010-07-15,None,44818517,416006.0,4307.0,887803387673548,5576589.0,1954,2010,56,50-60
52560,5576657,116286,0,2010-06-30,None,2010-06-30,None,44818517,276661.0,119260.0,887713387509358,5576656.0,1927,2010,83,80-90
52561,5576780,116288,0,2010-07-02,None,2010-07-02,None,44818517,190386.0,9991.0,887963386801135,5576779.0,1953,2010,57,50-60
52562,5576779,116288,0,2010-07-15,None,2010-07-15,None,44818517,25182.0,13889.0,887963385988392,5576778.0,1953,2010,57,50-60
52563,5576706,116288,9201,2010-07-09,None,2010-07-10,None,44818517,3683.0,670.0,196931176976105,NaN,1953,2010,57,50-60
52564,5576959,116292,0,2010-06-28,None,2010-06-28,None,44818517,89783.0,49049.0,887223388420198,5576958.0,1930,2010,80,70-80
52565,5576973,116292,0,2010-07-12,None,2010-07-12,None,44818517,634337.0,238815.0,887633384912121,5576972.0,1930,2010,80,70-80
52566,5576981,116292,0,2010-07-15,None,2010-07-15,None,44818517,221768.0,25048.0,887953385875924,5576980.0,1930,2010,80,70-80
52567,5576893,116291,0,2010-07-14,None,2010-07-14,None,44818517,38812.0,22616.0,887273385962688,5576892.0,1943,2010,67,60-70
52568,5576932,116291,0,2010-07-10,None,2010-07-10,None,44818517,142000.0,68057.0,887883388564937,5576931.0,1943,2010,67,60-70
52569,5577515,116303,0,2010-07-04,None,2010-07-04,None,44818517,440511.0,12887.0,887363385275026,5577514.0,1940,2010,70,60-70
52570,5577559,116303,0,2010-07-13,None,2010-07-13,None,44818517,10301.0,6832.0,887823385688854,5577558.0,1940,2010,70,60-70
52571,5577950,116314,0,2010-06-28,None,2010-06-28,None,44818517,97963.0,49827.0,887483388653416,5577949.0,1934,2010,76,70-80
52572,5577990,116314,0,2010-06-30,None,2010-06-30,None,44818517,5.0,5.0,887933389547980,5577989.0,1934,2010,76,70-80
52573,5577794,116310,0,2010-07-04,None,2010-07-04,None,44818517,480108.0,6053.0,887463388583184,5577793.0,1960,2010,50,40-50
52574,5577847,116311,0,2010-06-28,None,2010-06-28,None,44818517,396232.0,114841.0,887133385017307,5577846.0,1960,2010,50,40-50
52575,5578248,116322,0,2010-07-10,None,2010-07-19,None,44818517,479195.0,54562.0,887453387433693,5578247.0,1951,2010,59,50-60
52576,5578383,116324,0,2010-07-14,None,2010-07-23,None,44818517,356542.0,147270.0,887913385953512,5578382.0,1956,2010,54,50-60
52577,5578754,116335,0,2010-07-02,None,2010-07-02,None,44818517,20643.0,26778.0,887333386018732,5578753.0,1953,2010,57,50-60
52578,5578678,116332,0,2010-07-02,None,2010-07-02,None,44818517,219133.0,97974.0,887793389150930,5578677.0,1925,2010,85,80-90
52579,5578816,116337,0,2010-07-15,None,2010-07-15,None,44818517,3324.0,2310.0,887683387420433,5578815.0,1940,2010,70,60-70
52580,5578823,116337,0,2010-07-09,None,2010-07-09,None,44818517,250792.0,109740.0,887863384973051,5578822.0,1940,2010,70,60-70
52581,5578897,116339,0,2010-07-10,None,2010-07-10,None,44818517,7262.0,26484.0,887083387666641,5578896.0,1920,2010,90,80-90
52582,5578931,116339,0,2010-07-15,None,2010-07-15,None,44818517,352.0,40.0,887333388842512,5578930.0,1920,2010,90,80-90
52583,5579156,116342,0,2010-07-13,None,2010-07-13,None,44818517,91766.0,45530.0,887103388905386,5579155.0,1930,2010,80,70-80
52584,5579332,116347,0,2010-07-09,None,2010-07-09,None,44818517,196780.0,89555.0,887523388182751,5579331.0,1939,2010,71,70-80
52585,5579272,116344,9202,2010-07-14,None,2010-07-14,None,44818517,16769.0,10610.0,542332281425072,5579271.0,1941,2010,69,60-70
52586,5579380,116349,0,2010-07-04,None,2010-07-04,None,44818517,302380.0,128257.0,887053388319393,5579379.0,1916,2010,94,90-100
52587,5579116,116341,0,2010-07-04,None,2010-07-04,None,44818517,401922.0,163155.0,887743387316815,5579115.0,1935,2010,75,70-80

### Function for table with age frequency slot

In [39]:
def table_age_freq(dates, dataframe):
    an = {}
    for i in dates:
        x = dataframe[dataframe['visit_start_date'] == i]['Age_Slot'].value_counts()
        x = x.tolist()
        #m = pd.DataFrame(x)
        #gr = [{'Date': i , 'Freq':x}]
        an[i] = x
    
    Age_slot_dataframe = pd.DataFrame(an).T   # Transposing the dataframe
    labels= ['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100']
    Age_slot_dataframe.columns = labels
    Age_slot_dataframe.columns = reversed(Age_slot_dataframe.columns)
    Age_slot_dataframe
    #d = df[[i, synpuf_visit_occurence_filtered_withAge[synpuf_visit_occurence_filtered_withAge['visit_start_date'] == i]['Age_Slot'].value_counts()] for i in list_of_dates_case()]
    Age_slot_dataframe['Dates'] =  pd.to_datetime(Age_slot_dataframe.index)
    #Age_slot_dataframe['Dates'] = Age_slot_dataframe.index
    Age_slot_dataframe['day_of_week'] = Age_slot_dataframe['Dates'].dt.day_name()
    #df['day_of_week'] = df['my_dates'].dt.day_name()
    Age_slot_dataframe = Age_slot_dataframe.drop('Dates', axis =1)
    return(Age_slot_dataframe)

# Age slot frequency on heat wave days
## Final Heatwave Table_1 CASE

In [40]:
case_table_1 = table_age_freq(list_of_dates_case, synpuf_visit_occurence_filtered_withAge)
case_table_1

,90-100,80-90,70-80,60-70,50-60,40-50,30-40,20-30,10-20,0-10,day_of_week
1991-07-20,0,0,0,0,0,0,0,0,0,0,Saturday
1991-07-21,0,0,0,0,0,0,0,0,0,0,Sunday
1991-07-23,0,0,0,0,0,0,0,0,0,0,Tuesday
1993-07-07,0,0,0,0,0,0,0,0,0,0,Wednesday
1993-07-08,0,0,0,0,0,0,0,0,0,0,Thursday
1993-07-09,0,0,0,0,0,0,0,0,0,0,Friday
1993-07-10,0,0,0,0,0,0,0,0,0,0,Saturday
1994-07-08,0,0,0,0,0,0,0,0,0,0,Friday
1994-07-09,0,0,0,0,0,0,0,0,0,0,Saturday
1995-07-14,0,0,0,0,0,0,0,0,0,0,Friday
1995-07-15,0,0,0,0,0,0,0,0,0,0,Saturday
1995-07-26,0,0,0,0,0,0,0,0,0,0,Wednesday
1995-07-27,0,0,0,0,0,0,0,0,0,0,Thursday
1995-07-28,0,0,0,0,0,0,0,0,0,0,Friday
1995-07-29,0,0,0,0,0,0,0,0,0,0,Saturday
1997-07-15,0,0,0,0,0,0,0,0,0,0,Tuesday
1997-07-16,0,0,0,0,0,0,0,0,0,0,Wednesday
1997-07-17,0,0,0,0,0,0,0,0,0,0,Thursday
1999-07-04,0,0,0,0,0,0,0,0,0,0,Sunday
1999-07-05,0,0,0,0,0,0,0,0,0,0,Monday
1999-07-06,0,0,0,0,0,0,0,0,0,0,Tuesday
2001-08-07,0,0,0,0,0,0,0,0,0,0,Tuesday
2001-08-08,0,0,0,0,0,0,0,0,0,0,Wednesday
2001-08-09,0,0,0,0,0,0,0,0,0,0,Thursday
2001-08-10,0,0,0,0,0,0,0,0,0,0,Friday
2002-07-03,0,0,0,0,0,0,0,0,0,0,Wednesday
2002-07-04,0,0,0,0,0,0,0,0,0,0,Thursday
2005-08-13,0,0,0,0,0,0,0,0,0,0,Saturday
2005-08-14,0,0,0,0,0,0,0,0,0,0,Sunday
2006-08-01,0,0,0,0,0,0,0,0,0,0,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...
2013-07-06,0,0,0,0,0,0,0,0,0,0,Saturday
2013-07-07,0,0,0,0,0,0,0,0,0,0,Sunday
2013-07-14,0,0,0,0,0,0,0,0,0,0,Sunday
2013-07-15,0,0,0,0,0,0,0,0,0,0,Monday
2013-07-18,0,0,0,0,0,0,0,0,0,0,Thursday
2013-07-19,0,0,0,0,0,0,0,0,0,0,Friday
2013-07-20,0,0,0,0,0,0,0,0,0,0,Saturday
2015-07-19,0,0,0,0,0,0,0,0,0,0,Sunday
2015-07-20,0,0,0,0,0,0,0,0,0,0,Monday
2015-07-28,0,0,0,0,0,0,0,0,0,0,Tuesday
2015-07-29,0,0,0,0,0,0,0,0,0,0,Wednesday
2016-08-10,0,0,0,0,0,0,0,0,0,0,Wednesday
2016-08-11,0,0,0,0,0,0,0,0,0,0,Thursday
2016-08-12,0,0,0,0,0,0,0,0,0,0,Friday
2016-08-13,0,0,0,0,0,0,0,0,0,0,Saturday
2016-08-14,0,0,0,0,0,0,0,0,0,0,Sunday
2016-08-15,0,0,0,0,0,0,0,0,0,0,Monday
2017-07-19,0,0,0,0,0,0,0,0,0,0,Wednesday
2017-07-20,0,0,0,0,0,0,0,0,0,0,Thursday
2017-07-21,0,0,0,0,0,0,0,0,0,0,Friday
2018-07-01,0,0,0,0,0,0,0,0,0,0,Sunday
2018-07-02,0,0,0,0,0,0,0,0,0,0,Monday
2018-07-03,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-08-06,0,0,0,0,0,0,0,0,0,0,Monday
2018-08-07,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-08-08,0,0,0,0,0,0,0,0,0,0,Wednesday
2018-08-28,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-08-29,0,0,0,0,0,0,0,0,0,0,Wednesday
2018-09-03,0,0,0,0,0,0,0,0,0,0,Monday
2018-09-05,0,0,0,0,0,0,0,0,0,0,Wednesday


## Control Table - 1 (Immediate days before the heatwave days)

In [41]:
control_table_1 = table_age_freq(list_of_dates_control,synpuf_visit_occurence_filtered_CONTROL_with_age)
control_table_1

,90-100,80-90,70-80,60-70,50-60,40-50,30-40,20-30,10-20,0-10,day_of_week
1991-07-17,0,0,0,0,0,0,0,0,0,0,Wednesday
1991-07-18,0,0,0,0,0,0,0,0,0,0,Thursday
1991-07-19,0,0,0,0,0,0,0,0,0,0,Friday
1993-07-03,0,0,0,0,0,0,0,0,0,0,Saturday
1993-07-04,0,0,0,0,0,0,0,0,0,0,Sunday
1993-07-05,0,0,0,0,0,0,0,0,0,0,Monday
1993-07-06,0,0,0,0,0,0,0,0,0,0,Tuesday
1994-07-06,0,0,0,0,0,0,0,0,0,0,Wednesday
1994-07-07,0,0,0,0,0,0,0,0,0,0,Thursday
1995-07-12,0,0,0,0,0,0,0,0,0,0,Wednesday
1995-07-13,0,0,0,0,0,0,0,0,0,0,Thursday
1995-07-22,0,0,0,0,0,0,0,0,0,0,Saturday
1995-07-23,0,0,0,0,0,0,0,0,0,0,Sunday
1995-07-24,0,0,0,0,0,0,0,0,0,0,Monday
1995-07-25,0,0,0,0,0,0,0,0,0,0,Tuesday
1997-07-12,0,0,0,0,0,0,0,0,0,0,Saturday
1997-07-13,0,0,0,0,0,0,0,0,0,0,Sunday
1997-07-14,0,0,0,0,0,0,0,0,0,0,Monday
1999-07-01,0,0,0,0,0,0,0,0,0,0,Thursday
1999-07-02,0,0,0,0,0,0,0,0,0,0,Friday
1999-07-03,0,0,0,0,0,0,0,0,0,0,Saturday
2001-08-03,0,0,0,0,0,0,0,0,0,0,Friday
2001-08-04,0,0,0,0,0,0,0,0,0,0,Saturday
2001-08-05,0,0,0,0,0,0,0,0,0,0,Sunday
2001-08-06,0,0,0,0,0,0,0,0,0,0,Monday
2002-07-01,0,0,0,0,0,0,0,0,0,0,Monday
2002-07-02,0,0,0,0,0,0,0,0,0,0,Tuesday
2005-08-11,0,0,0,0,0,0,0,0,0,0,Thursday
2005-08-12,0,0,0,0,0,0,0,0,0,0,Friday
2006-07-29,0,0,0,0,0,0,0,0,0,0,Saturday
...,...,...,...,...,...,...,...,...,...,...,...
2011-07-20,0,0,0,0,0,0,0,0,0,0,Wednesday
2013-07-04,0,0,0,0,0,0,0,0,0,0,Thursday
2013-07-05,0,0,0,0,0,0,0,0,0,0,Friday
2013-07-12,0,0,0,0,0,0,0,0,0,0,Friday
2013-07-13,0,0,0,0,0,0,0,0,0,0,Saturday
2013-07-16,0,0,0,0,0,0,0,0,0,0,Tuesday
2013-07-17,0,0,0,0,0,0,0,0,0,0,Wednesday
2015-07-17,0,0,0,0,0,0,0,0,0,0,Friday
2015-07-18,0,0,0,0,0,0,0,0,0,0,Saturday
2015-07-26,0,0,0,0,0,0,0,0,0,0,Sunday
2015-07-27,0,0,0,0,0,0,0,0,0,0,Monday
2016-08-04,0,0,0,0,0,0,0,0,0,0,Thursday
2016-08-05,0,0,0,0,0,0,0,0,0,0,Friday
2016-08-06,0,0,0,0,0,0,0,0,0,0,Saturday
2016-08-07,0,0,0,0,0,0,0,0,0,0,Sunday
2016-08-08,0,0,0,0,0,0,0,0,0,0,Monday
2016-08-09,0,0,0,0,0,0,0,0,0,0,Tuesday
2017-07-16,0,0,0,0,0,0,0,0,0,0,Sunday
2017-07-17,0,0,0,0,0,0,0,0,0,0,Monday
2017-07-18,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-06-28,0,0,0,0,0,0,0,0,0,0,Thursday
2018-06-29,0,0,0,0,0,0,0,0,0,0,Friday
2018-06-30,0,0,0,0,0,0,0,0,0,0,Saturday
2018-08-03,0,0,0,0,0,0,0,0,0,0,Friday
2018-08-04,0,0,0,0,0,0,0,0,0,0,Saturday
2018-08-05,0,0,0,0,0,0,0,0,0,0,Sunday
2018-08-26,0,0,0,0,0,0,0,0,0,0,Sunday
2018-08-27,0,0,0,0,0,0,0,0,0,0,Monday
2018-09-01,0,0,0,0,0,0,0,0,0,0,Saturday
2018-09-02,0,0,0,0,0,0,0,0,0,0,Sunday

## Control Table - 2 (7 days range before the heatwave days)

In [42]:
control_table_2 = table_age_freq(list_of_dates_control_7, synpuf_visit_occurence_filtered_CONTROL_with_age_7)
control_table_2

,90-100,80-90,70-80,60-70,50-60,40-50,30-40,20-30,10-20,0-10,day_of_week
1991-07-13,0,0,0,0,0,0,0,0,0,0,Saturday
1991-07-14,0,0,0,0,0,0,0,0,0,0,Sunday
1991-07-15,0,0,0,0,0,0,0,0,0,0,Monday
1991-07-16,0,0,0,0,0,0,0,0,0,0,Tuesday
1991-07-17,0,0,0,0,0,0,0,0,0,0,Wednesday
1991-07-18,0,0,0,0,0,0,0,0,0,0,Thursday
1991-07-19,0,0,0,0,0,0,0,0,0,0,Friday
1993-06-30,0,0,0,0,0,0,0,0,0,0,Wednesday
1993-07-01,0,0,0,0,0,0,0,0,0,0,Thursday
1993-07-02,0,0,0,0,0,0,0,0,0,0,Friday
1993-07-03,0,0,0,0,0,0,0,0,0,0,Saturday
1993-07-04,0,0,0,0,0,0,0,0,0,0,Sunday
1993-07-05,0,0,0,0,0,0,0,0,0,0,Monday
1993-07-06,0,0,0,0,0,0,0,0,0,0,Tuesday
1994-07-01,0,0,0,0,0,0,0,0,0,0,Friday
1994-07-02,0,0,0,0,0,0,0,0,0,0,Saturday
1994-07-03,0,0,0,0,0,0,0,0,0,0,Sunday
1994-07-04,0,0,0,0,0,0,0,0,0,0,Monday
1994-07-05,0,0,0,0,0,0,0,0,0,0,Tuesday
1994-07-06,0,0,0,0,0,0,0,0,0,0,Wednesday
1994-07-07,0,0,0,0,0,0,0,0,0,0,Thursday
1995-07-07,0,0,0,0,0,0,0,0,0,0,Friday
1995-07-08,0,0,0,0,0,0,0,0,0,0,Saturday
1995-07-09,0,0,0,0,0,0,0,0,0,0,Sunday
1995-07-10,0,0,0,0,0,0,0,0,0,0,Monday
1995-07-11,0,0,0,0,0,0,0,0,0,0,Tuesday
1995-07-12,0,0,0,0,0,0,0,0,0,0,Wednesday
1995-07-13,0,0,0,0,0,0,0,0,0,0,Thursday
1995-07-19,0,0,0,0,0,0,0,0,0,0,Wednesday
1995-07-20,0,0,0,0,0,0,0,0,0,0,Thursday
...,...,...,...,...,...,...,...,...,...,...,...
2017-07-14,0,0,0,0,0,0,0,0,0,0,Friday
2017-07-15,0,0,0,0,0,0,0,0,0,0,Saturday
2017-07-16,0,0,0,0,0,0,0,0,0,0,Sunday
2017-07-17,0,0,0,0,0,0,0,0,0,0,Monday
2017-07-18,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-06-24,0,0,0,0,0,0,0,0,0,0,Sunday
2018-06-25,0,0,0,0,0,0,0,0,0,0,Monday
2018-06-26,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-06-27,0,0,0,0,0,0,0,0,0,0,Wednesday
2018-06-28,0,0,0,0,0,0,0,0,0,0,Thursday
2018-06-29,0,0,0,0,0,0,0,0,0,0,Friday
2018-06-30,0,0,0,0,0,0,0,0,0,0,Saturday
2018-07-30,0,0,0,0,0,0,0,0,0,0,Monday
2018-07-31,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-08-01,0,0,0,0,0,0,0,0,0,0,Wednesday
2018-08-02,0,0,0,0,0,0,0,0,0,0,Thursday
2018-08-03,0,0,0,0,0,0,0,0,0,0,Friday
2018-08-04,0,0,0,0,0,0,0,0,0,0,Saturday
2018-08-05,0,0,0,0,0,0,0,0,0,0,Sunday
2018-08-21,0,0,0,0,0,0,0,0,0,0,Tuesday
2018-08-22,0,0,0,0,0,0,0,0,0,0,Wednesday
2018-08-23,0,0,0,0,0,0,0,0,0,0,Thursday
2018-08-24,0,0,0,0,0,0,0,0,0,0,Friday
2018-08-25,0,0,0,0,0,0,0,0,0,0,Saturday
2018-08-26,0,0,0,0,0,0,0,0,0,0,Sunday
2018-08-27,0,0,0,0,0,0,0,0,0,0,Monday
2018-08-30,0,0,0,0,0,0,0,0,0,0,Thursday
2018-08-31,0,0,0,0,0,0,0,0,0,0,Friday
2018-09-01,0,0,0,0,0,0,0,0,0,0,Saturday
2018-09-02,0,0,0,0,0,0,0,0,0,0,Sunday

# Final Table - 2

In [43]:
Age_slot_dataframe = table_age_freq(list_of_dates_case, synpuf_visit_occurence_filtered_withAge)
Age_slot_dataframe['Total'] = Age_slot_dataframe.sum(axis = 1)
temp_df1 =  Age_slot_dataframe.reset_index()

In [44]:
temp_df2 = refined_list.reset_index()
temp_df2['patient_freq'] = temp_df1['Total']
#refined_list.head(50)
patient_count_on_heatwave = temp_df2.set_index(['index_count','index_value'])
patient_count_on_heatwave['Day'] = pd.to_datetime(patient_count_on_heatwave.DateTime)
patient_count_on_heatwave['day_of_week'] = patient_count_on_heatwave['Day'].dt.day_name()
#df['day_of_week'] = df['my_dates'].dt.day_name()
patient_count_on_heatwave = patient_count_on_heatwave.drop('Day', axis =1)
patient_count_on_heatwave

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           200          1991-07-20  20.2884    30.1610  36.4549
            201          1991-07-21  20.9882    30.1809  35.8746
            203          1991-07-23  22.2694    30.1111  35.5850
1           918          1993-07-07  22.2687    29.8566  34.9479
            919          1993-07-08  21.7611    31.6063  36.3469
            920          1993-07-09  19.3806    32.3365  37.4773
            921          1993-07-10  20.2286    31.6914  37.5471
2           1284         1994-07-08  22.5519    29.3566  33.6633
            1285         1994-07-09  22.2383    28.8062  33.3326
3           1655         1995-07-14  20.7647    29.6513  36.2968
            1656         1995-07-15  22.6235    31.7269  38.2673
4           1667         1995-07-26  22.4758    28.9965  32.6266
            1668         1995-07-27  21.7881    29.8467  33.1371
            1669         1995-07-28  22.2804    29.1561  31.9466
            1670         1995-07-29  21.8158    30.1614  33.8566
5           2387         1997-07-15  20.6909    29.8889  35.7787
            2388         1997-07-16  21.3333    29.8587  34.2687
            2389         1997-07-17  19.5592    30.1135  34.5879
6           3106         1999-07-04  22.5213    30.8131  36.1088
            3107         1999-07-05  22.5430    32.7128  37.9979
            3108         1999-07-06  21.7924    31.5378  36.9685
7           3871         2001-08-07  20.5326    29.3802  35.5342
            3872         2001-08-08  21.1636    30.4502  35.7546
            3873         2001-08-09  20.7511    31.1055  36.6652
            3874         2001-08-10  22.7621    29.9905  33.8953
8           4201         2002-07-03  21.1851    31.2508  36.7110
            4202         2002-07-04  20.5538    31.5305  36.5411
9           5338         2005-08-13  22.8777    30.8525  35.2331
            5339         2005-08-14  22.8510    31.1872  35.0923
10          5691         2006-08-01  21.4175    29.7827  35.5960
...                             ...      ...        ...      ...
14          8222         2013-07-06  19.8732    30.7530  37.1491
            8223         2013-07-07  19.6039    30.9673  37.8262
15          8230         2013-07-14  19.6169    30.1955  36.8785
            8231         2013-07-15  19.7339    30.9795  37.6445
16          8234         2013-07-18  19.6346    31.4111  38.7649
            8235         2013-07-19  20.4954    32.1772  39.0952
            8236         2013-07-20  20.7304    31.4933  36.9967
17          8965         2015-07-19  18.4141    31.0241  34.4315
            8966         2015-07-20  22.1983    30.4190  34.3315
18          8974         2015-07-28  20.6575    29.5592  34.2316
            8975         2015-07-29  20.7373    30.3287  34.6812
19          9353         2016-08-10  21.7220    28.6762  30.8089
            9354         2016-08-11  23.0205    29.1112  34.0089
            9355         2016-08-12  23.4715    30.5362  34.6089
            9356         2016-08-13  23.9413    31.8512  35.6589
            9357         2016-08-14  22.2425    30.2562  34.8889
            9358         2016-08-15  21.5992    29.3762  33.0289
20          9696         2017-07-19  21.3950    29.3367  33.5270
            9697         2017-07-20  20.7310    29.7537  34.8590
            9698         2017-07-21  20.7552    29.5747  33.7770
21          10043        2018-07-01  20.8945    30.3668  35.5044
            10044        2018-07-02  21.9748    30.1768  34.8174
            10045        2018-07-03  23.0943    28.9478  33.0745
22          10079        2018-08-06  21.9798    29.2395  33.4449
            10080        2018-08-07  23.1125    27.7245  32.0139
            10081        2018-08-08  22.7500    28.0130  32.3509
23          10101        2018-08-28  22.3603    30.3640  34.6349
            10102        2018-08-29  22.5407    29.9880  33.9239
24          10107        2018-09-03  21.5176    28.7953  32.8329
            10109        2018-09-05  21.7569    28.7958  32.2679

                         Apparent temp  patient_freq day_of_week
index_count index_value
0           200              33.623807             0    Saturday
            201              34.085534             0      Sunday
            203              34.864104             0     Tuesday
1           918              34.610654             0   Wednesday
            919              36.007908             0    Thursday
            920              35.235278             0      Friday
            921              35.107954             0    Saturday
2           1284             34.307860             0      Friday
            1285             33.545855             0    Saturday
3           1655             33.416336             0      Friday
            1656             36.713427             0    Saturday
4           1667             33.897493             0   Wednesday
            1668             34.276856             0    Thursday
            1669             33.922332             0      Friday
            1670             34.608147             0    Saturday
5           2387             33.605701             0     Tuesday
            2388             33.988726             0   Wednesday
            2389             33.132022             0    Thursday
6           3106             35.734518             0      Sunday
            3107             37.637782             0      Monday
            3108             35.960676             0     Tuesday
7           3871             33.000210             0     Tuesday
            3872             34.466338             0   Wednesday
            3873             34.853172             0    Thursday
            3874             35.083689             0      Friday
8           4201             35.276065             0   Wednesday
            4202             35.150935             0    Thursday
9           5338             36.021239             0    Saturday
            5339             36.335250             0      Sunday
10          5691             33.968256             0     Tuesday
...                                ...           ...         ...
14          8222             33.957126             0    Saturday
            8223             34.007483             0      Sunday
15          8230             33.248115             0      Sunday
            8231             34.097853             0      Monday
16          8234             34.467051             0    Thursday
            8235             35.757077             0      Friday
            8236             35.225507             0    Saturday
17          8965             33.371865             0      Sunday
            8966             35.121783             0      Monday
18          8974             33.256849             0     Tuesday
            8975             34.072273             0   Wednesday
19          9353             33.069376             0   Wednesday
            9354             34.390667             0    Thursday
            9355             36.127926             0      Friday
            9356             37.775836             0    Saturday
            9357             34.990014             0      Sunday
            9358             33.683782             0      Monday
20          9696             33.510194             0   Wednesday
            9697             33.496726             0    Thursday
            9698             33.334160             0      Friday
21          10043            34.210275             0      Sunday
            10044            34.729984             0      Monday
            10045            34.280318             0     Tuesday
22          10079            33.801671             0      Monday
            10080            33.077224             0     Tuesday
            10081            33.109628             0   Wednesday
23          10101            35.177556             0     Tuesday
            10102            34.927744             0   Wednesday
24          10107            33.052537             0      Monday
            10109            33.211474             0   Wednesday

[71 rows x 7 columns]

# Control Table - immediete days before the case days

In [45]:
#Age_slot_dataframe_control
Age_slot_dataframe_control = control_table_1 
Age_slot_dataframe_control['Total'] = Age_slot_dataframe_control.sum(axis = 1)
temp_df1_control =  Age_slot_dataframe_control.reset_index()

In [46]:


temp_df2_control = weather_data_ctrl_immediate_days.reset_index()
temp_df2_control['patient_freq'] = temp_df1_control['Total']
#refined_list.head(50)
patient_count_on_heatwave_control = temp_df2_control.set_index(['index_count','index_value'])
#Age_slot_dataframe['Total']
patient_count_on_heatwave_control['Day'] = pd.to_datetime(patient_count_on_heatwave_control.DateTime)
patient_count_on_heatwave_control['day_of_week'] = patient_count_on_heatwave_control['Day'].dt.day_name()
#df['day_of_week'] = df['my_dates'].dt.day_name()
patient_count_on_heatwave_control = patient_count_on_heatwave_control.drop('Day', axis =1)
patient_count_on_heatwave_control

                         index    DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           197            197  1991-07-17  17.0134    25.9707  32.8747
            198            198  1991-07-18  18.5805    27.7155  34.5947
            199            199  1991-07-19  21.0015    28.6158  34.1048
1           914            914  1993-07-03  18.6796    24.4466  30.3073
            915            915  1993-07-04  19.2947    29.3418  33.6079
            916            916  1993-07-05  17.1997    27.0365  31.5473
            917            917  1993-07-06  19.8462    27.1067  33.4175
2           1282          1282  1994-07-06  21.6105    27.8016  33.3728
            1283          1283  1994-07-07  21.1058    28.9021  34.3335
3           1653          1653  1995-07-12  17.4819    24.7512  29.0466
            1654          1654  1995-07-13  19.0447    26.2368  32.5672
4           1663          1663  1995-07-22  19.9964    27.0815  29.3766
            1664          1664  1995-07-23  21.4925    27.4265  30.9676
            1665          1665  1995-07-24  20.0966    27.8320  31.6376
            1666          1666  1995-07-25  21.9616    27.9970  30.9874
5           2384          2384  1997-07-12  13.5190    23.9886  30.3683
            2385          2385  1997-07-13  16.3526    26.0637  32.7586
            2386          2386  1997-07-14  18.0509    27.7534  34.1776
6           3103          3103  1999-07-01  19.7055    24.7881  26.6587
            3104          3104  1999-07-02  20.2746    26.9132  29.8883
            3105          3105  1999-07-03  20.8278    28.1075  32.2677
7           3867          3867  2001-08-03  17.6178    24.6601  31.0144
            3868          3868  2001-08-04  19.6287    25.8505  29.9549
            3869          3869  2001-08-05  20.5761    26.7205  30.7051
            3870          3870  2001-08-06  21.2436    28.5052  33.8444
8           4199          4199  2002-07-01  17.1751    26.1805  31.0305
            4200          4200  2002-07-02  20.0481    28.3609  34.8814
9           5336          5336  2005-08-11  19.8854    29.2124  34.2227
            5337          5337  2005-08-12  20.1675    29.1624  33.9523
10          5688          5688  2006-07-29  19.3295    27.0917  32.6882
...                        ...         ...      ...        ...      ...
13          7505          7505  2011-07-20  20.6268    28.1176  33.1215
14          8220          8220  2013-07-04  19.4297    29.2288  35.8140
            8221          8221  2013-07-05  19.6030    29.7583  36.6969
15          8228          8228  2013-07-12  17.7960    26.0241  28.7283
            8229          8229  2013-07-13  18.8104    26.5855  30.4026
16          8232          8232  2013-07-16  18.2833    30.2841  37.0780
            8233          8233  2013-07-17  17.8691    30.4163  36.4924
17          8963          8963  2015-07-17  15.6228    24.4486  26.8306
            8964          8964  2015-07-18  19.8504    26.1887  29.7111
18          8972          8972  2015-07-26  17.7677    27.2038  31.3511
            8973          8973  2015-07-27  19.4714    26.6787  29.9109
19          9347          9347  2016-08-04  16.8534    24.1062  27.6489
            9348          9348  2016-08-05  18.5832    26.0612  28.6989
            9349          9349  2016-08-06  21.0484    26.1912  30.7989
            9350          9350  2016-08-07  15.4879    26.1412  30.4789
            9351          9351  2016-08-08  14.0293    25.6262  29.7089
            9352          9352  2016-08-09  15.4633    27.5762  30.7389
20          9693          9693  2017-07-16  17.8753    25.9932  29.8050
            9694          9694  2017-07-17  20.2978    26.4332  29.6120
            9695          9695  2017-07-18  21.0008    27.4957  30.7230
21          10040        10040  2018-06-28  18.8445    25.2229  28.8354
            10041        10041  2018-06-29  18.6548    27.4629  32.8084
            10042        10042  2018-06-30  18.6563    29.3588  33.9344
22          10076        10076  2018-08-03  21.8652    26.3780  29.2149
            10077        10077  2018-08-04  20.2806    26.5840  30.7289
            10078        10078  2018-08-05  20.8589    28.8190  32.9249
23          10099        10099  2018-08-26  19.3282    25.3190  28.7739
            10100        10100  2018-08-27  21.3633    28.0335  31.5979
24          10105        10105  2018-09-01  17.9422    23.0238  25.8699
            10106        10106  2018-09-02  18.7967    25.1263  27.9879

                         Apparent temp  patient_freq day_of_week
index_count index_value
0           197              27.589549             0   Wednesday
            198              30.177302             0    Thursday
            199              32.538369             0      Friday
1           914              26.984510             0    Saturday
            915              32.207717             0      Sunday
            916              28.746475             0      Monday
            917              30.316296             0     Tuesday
2           1282             32.126100             0   Wednesday
            1283             32.890146             0    Thursday
3           1653             26.624630             0   Wednesday
            1654             28.974698             0    Thursday
4           1663             30.382808             0    Saturday
            1664             31.675433             0      Sunday
            1665             31.190270             0      Monday
            1666             32.554390             0     Tuesday
5           2384             23.986948             0    Saturday
            2385             27.344653             0      Sunday
            2386             29.918155             0      Monday
6           3103             27.926464             0    Thursday
            3104             30.386930             0      Friday
            3105             31.921953             0    Saturday
7           3867             26.607059             0      Friday
            3868             28.936271             0    Saturday
            3869             30.383828             0      Sunday
            3870             32.584914             0      Monday
8           4199             27.882673             0      Monday
            4200             31.686207             0     Tuesday
9           5336             32.433191             0    Thursday
            5337             32.556365             0      Friday
10          5688             29.991682             0    Saturday
...                                ...           ...         ...
13          7505             31.804507             0   Wednesday
14          8220             32.175380             0    Thursday
            8221             32.805198             0      Friday
15          8228             28.059429             0      Friday
            8229             29.185604             0    Saturday
16          8232             32.562865             0     Tuesday
            8233             32.465165             0   Wednesday
17          8963             25.382208             0      Friday
            8964             29.406355             0    Saturday
18          8972             29.216652             0      Sunday
            8973             29.665400             0      Monday
19          9347             25.653330             0    Thursday
            9348             28.534463             0      Friday
            9349             30.158490             0    Saturday
            9350             27.000441             0      Sunday
            9351             25.829808             0      Monday
            9352             28.415182             0     Tuesday
20          9693             28.071994             0      Sunday
            9694             29.924211             0      Monday
            9695             31.424540             0     Tuesday
21          10040            27.850825             0    Thursday
            10041            29.968547             0      Friday
            10042            31.853927             0    Saturday
22          10076            30.880463             0      Friday
            10077            30.063428             0    Saturday
            10078            32.649020             0      Sunday
23          10099            28.228850             0      Sunday
            10100            32.194075             0      Monday
24          10105            25.157072             0    Saturday
            10106            27.727276             0      Sunday

[70 rows x 8 columns]

# Control table 7 day range before the case days

In [47]:
#Age_slot_dataframe_control
Age_slot_dataframe_control_7 = control_table_2
Age_slot_dataframe_control_7['Total'] = Age_slot_dataframe_control_7.sum(axis = 1)
temp_df1_control_7 =  Age_slot_dataframe_control_7.reset_index()

In [48]:
temp_df2_control_7 = weather_data_ctrl_immediate_days_7.reset_index()
temp_df2_control_7['patient_freq'] = temp_df1_control_7['Total']
#refined_list.head(50)
patient_count_on_heatwave_control_7 = temp_df2_control_7.set_index(['index_count','index_value'])
#Age_slot_dataframe['Total']
patient_count_on_heatwave_control_7['Day'] = pd.to_datetime(patient_count_on_heatwave_control_7.DateTime)
patient_count_on_heatwave_control_7['day_of_week'] = patient_count_on_heatwave_control_7['Day'].dt.day_name()
#df['day_of_week'] = df['my_dates'].dt.day_name()
patient_count_on_heatwave_control_7 = patient_count_on_heatwave_control_7.drop('Day', axis =1)
patient_count_on_heatwave_control_7

                           DateTime      DPT  Mean Temp  MaxTemp  \
index_count index_value
0           193          1991-07-13  19.6937    25.1258  28.3748
            194          1991-07-14  16.7824    25.7308  28.7651
            195          1991-07-15  13.7313    25.6411  30.4249
            196          1991-07-16  14.6237    24.9264  30.8755
            197          1991-07-17  17.0134    25.9707  32.8747
            198          1991-07-18  18.5805    27.7155  34.5947
            199          1991-07-19  21.0015    28.6158  34.1048
1           911          1993-06-30  15.9377    26.0314  29.4373
            912          1993-07-01  15.0508    23.9365  28.6070
            913          1993-07-02  15.3641    19.9864  21.4877
            914          1993-07-03  18.6796    24.4466  30.3073
            915          1993-07-04  19.2947    29.3418  33.6079
            916          1993-07-05  17.1997    27.0365  31.5473
            917          1993-07-06  19.8462    27.1067  33.4175
2           1277         1994-07-01  17.8006    24.5866  28.7229
            1278         1994-07-02  19.5143    25.6269  31.1836
            1279         1994-07-03  18.9709    26.4914  30.9925
            1280         1994-07-04  17.5349    24.1821  28.6437
            1281         1994-07-05  18.6795    23.9067  29.7427
            1282         1994-07-06  21.6105    27.8016  33.3728
            1283         1994-07-07  21.1058    28.9021  34.3335
3           1648         1995-07-07  18.5917    24.4520  27.6077
            1649         1995-07-08  17.2483    24.4171  28.7277
            1650         1995-07-09  11.7314    20.2165  25.0265
            1651         1995-07-10  14.3693    22.0614  27.2269
            1652         1995-07-11  16.6597    24.4314  27.4470
            1653         1995-07-12  17.4819    24.7512  29.0466
            1654         1995-07-13  19.0447    26.2368  32.5672
4           1660         1995-07-19  15.7605    25.5718  30.0071
            1661         1995-07-20  16.6783    25.6365  30.7970
...                             ...      ...        ...      ...
20          9692         2017-07-15  18.4747    24.8372  29.2680
            9693         2017-07-16  17.8753    25.9932  29.8050
            9694         2017-07-17  20.2978    26.4332  29.6120
            9695         2017-07-18  21.0008    27.4957  30.7230
21          10036        2018-06-24  18.2361    24.6469  29.4624
            10037        2018-06-25  12.6763    22.4039  27.7314
            10038        2018-06-26  13.0039    21.7174  25.0064
            10039        2018-06-27  16.6040    21.8769  23.0474
            10040        2018-06-28  18.8445    25.2229  28.8354
            10041        2018-06-29  18.6548    27.4629  32.8084
            10042        2018-06-30  18.6563    29.3588  33.9344
22          10072        2018-07-30  16.8643    23.2323  26.2295
            10073        2018-07-31  19.0037    25.0810  27.0819
            10074        2018-08-01  21.7129    27.1510  30.0398
            10075        2018-08-02  22.3598    27.4515  30.4559
            10076        2018-08-03  21.8652    26.3780  29.2149
            10077        2018-08-04  20.2806    26.5840  30.7289
            10078        2018-08-05  20.8589    28.8190  32.9249
23          10094        2018-08-21  19.2817    23.4105  25.1669
            10095        2018-08-22  18.6661    24.2805  28.9239
            10096        2018-08-23  13.0033    22.2140  26.0739
            10097        2018-08-24  14.6072    23.8280  28.2319
            10098        2018-08-25  17.7442    23.2320  26.6609
            10099        2018-08-26  19.3282    25.3190  28.7739
            10100        2018-08-27  21.3633    28.0335  31.5979
            10100        2018-08-27  21.3633    28.0335  31.5979
24          10103        2018-08-30  20.4944    27.6785  32.0149
            10104        2018-08-31  19.0452    22.6697  24.1869
            10105        2018-09-01  17.9422    23.0238  25.8699
            10106        2018-09-02  18.7967    25.1263  27.9879

                         Apparent temp  patient_freq day_of_week
index_count index_value
0           193              28.255025           0.0    Saturday
            194              27.231644           0.0      Sunday
            195              25.718047           0.0      Monday
            196              25.394786           0.0     Tuesday
            197              27.589549           0.0   Wednesday
            198              30.177302           0.0    Thursday
            199              32.538369           0.0      Friday
1           911              27.107569           0.0   Wednesday
            912              24.604738           0.0    Thursday
            913              20.824132           0.0      Friday
            914              26.984510           0.0    Saturday
            915              32.207717           0.0      Sunday
            916              28.746475           0.0      Monday
            917              30.316296           0.0     Tuesday
2           1277             26.633059           0.0      Friday
            1278             28.645500           0.0    Saturday
            1279             29.184846           0.0      Sunday
            1280             26.087340           0.0      Monday
            1281             26.447793           0.0     Tuesday
            1282             32.126100           0.0   Wednesday
            1283             32.890146           0.0    Thursday
3           1648             26.939753           0.0      Friday
            1649             26.168406           0.0    Saturday
            1650             19.546875           0.0      Sunday
            1651             22.434126           0.0      Monday
            1652             25.877259           0.0     Tuesday
            1653             26.624630           0.0   Wednesday
            1654             28.974698           0.0    Thursday
4           1660             26.564788           0.0   Wednesday
            1661             27.084616           0.0    Thursday
...                                ...           ...         ...
20          9692             27.256289           0.0    Saturday
            9693             28.071994           0.0      Sunday
            9694             29.924211           0.0      Monday
            9695             31.424540           0.0     Tuesday
21          10036            26.933115           0.0      Sunday
            10037            22.074012           0.0      Monday
            10038            21.520347           0.0     Tuesday
            10039            23.309739           0.0   Wednesday
            10040            27.850825           0.0    Thursday
            10041            29.968547           0.0      Friday
            10042            31.853927           0.0    Saturday
22          10072            24.790297           0.0      Monday
            10073            27.801965           0.0     Tuesday
            10074            31.547279           0.0   Wednesday
            10075            32.282189           0.0    Thursday
            10076            30.880463           0.0      Friday
            10077            30.063428           0.0    Saturday
            10078            32.649020           0.0      Sunday
23          10094            26.304332           0.0     Tuesday
            10095            26.811693           0.0   Wednesday
            10096            22.013729           0.0    Thursday
            10097            24.295597           0.0      Friday
            10098            25.255914           0.0    Saturday
            10099            28.228850           0.0      Sunday
            10100            32.194075           0.0      Monday
            10100            32.194075           0.0      Monday
24          10103            31.284742           NaN    Thursday
            10104            25.429292           NaN      Friday
            10105            25.157072           NaN    Saturday
            10106            27.727276           NaN      Sunday

[170 rows x 7 columns]

#ICD codes